<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Descriptive Statistics | desc_stats</title>
  <meta name="description" content="This is an R tutorial for the Ling 411 Class at Boğaziçi University in Fall 2022." />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Descriptive Statistics | desc_stats" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an R tutorial for the Ling 411 Class at Boğaziçi University in Fall 2022." />
  <meta name="github-repo" content="rstudio/ling_411" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Descriptive Statistics | desc_stats" />
  
  <meta name="twitter:description" content="This is an R tutorial for the Ling 411 Class at Boğaziçi University in Fall 2022." />
  

<meta name="author" content="Ümit Atlamaz" />


<meta name="date" content="2022-11-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="plotting-1.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Ling 411 - Fall 2022</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i><b>1.1</b> Disclaimer</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#some-great-resources"><i class="fa fa-check"></i><b>1.2</b> Some great resources</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#blocks"><i class="fa fa-check"></i><b>1.3</b> Blocks</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>2</b> Basics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basics.html"><a href="basics.html#basic-math-operations"><i class="fa fa-check"></i><b>2.1</b> Basic Math Operations</a></li>
<li class="chapter" data-level="2.2" data-path="basics.html"><a href="basics.html#operators"><i class="fa fa-check"></i><b>2.2</b> Operators</a></li>
<li class="chapter" data-level="2.3" data-path="basics.html"><a href="basics.html#variables-and-assignment"><i class="fa fa-check"></i><b>2.3</b> Variables and Assignment</a></li>
<li class="chapter" data-level="2.4" data-path="basics.html"><a href="basics.html#data-types"><i class="fa fa-check"></i><b>2.4</b> Data Types</a></li>
<li class="chapter" data-level="2.5" data-path="basics.html"><a href="basics.html#determining-the-data-type"><i class="fa fa-check"></i><b>2.5</b> Determining the data type</a></li>
<li class="chapter" data-level="2.6" data-path="basics.html"><a href="basics.html#changing-the-types"><i class="fa fa-check"></i><b>2.6</b> Changing the types</a></li>
<li class="chapter" data-level="2.7" data-path="basics.html"><a href="basics.html#installing-packages"><i class="fa fa-check"></i><b>2.7</b> Installing packages</a></li>
<li class="chapter" data-level="2.8" data-path="basics.html"><a href="basics.html#plotting"><i class="fa fa-check"></i><b>2.8</b> Plotting</a></li>
<li class="chapter" data-level="2.9" data-path="basics.html"><a href="basics.html#operators-and-functions-in-this-section"><i class="fa fa-check"></i><b>2.9</b> Operators and functions in this section</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="basics.html"><a href="basics.html#operators-1"><i class="fa fa-check"></i><b>2.9.1</b> Operators</a></li>
<li class="chapter" data-level="2.9.2" data-path="basics.html"><a href="basics.html#functions"><i class="fa fa-check"></i><b>2.9.2</b> Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data Structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#data-types-in-r"><i class="fa fa-check"></i><b>3.1</b> Data Types in R</a></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-in-r"><i class="fa fa-check"></i><b>3.2</b> Data Structures in R</a></li>
<li class="chapter" data-level="3.3" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.3</b> Vectors</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-structures.html"><a href="data-structures.html#what-are-vectors-good-for"><i class="fa fa-check"></i><b>3.3.1</b> What are vectors good for?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.4</b> Data Frames</a></li>
<li class="chapter" data-level="3.5" data-path="data-structures.html"><a href="data-structures.html#working-with-data-frames"><i class="fa fa-check"></i><b>3.5</b> Working with data frames</a></li>
<li class="chapter" data-level="3.6" data-path="data-structures.html"><a href="data-structures.html#functions-in-this-section"><i class="fa fa-check"></i><b>3.6</b> Functions in this section</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="working-with-data.html"><a href="working-with-data.html"><i class="fa fa-check"></i><b>4</b> Working with Data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="working-with-data.html"><a href="working-with-data.html#basic-dataframes"><i class="fa fa-check"></i><b>4.1</b> Basic dataframes</a></li>
<li class="chapter" data-level="4.2" data-path="working-with-data.html"><a href="working-with-data.html#tibbles"><i class="fa fa-check"></i><b>4.2</b> Tibbles</a></li>
<li class="chapter" data-level="4.3" data-path="working-with-data.html"><a href="working-with-data.html#beyond-toy-data"><i class="fa fa-check"></i><b>4.3</b> Beyond Toy Data</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="working-with-data.html"><a href="working-with-data.html#reading-data-from-a-csv-file"><i class="fa fa-check"></i><b>4.3.1</b> Reading data from a csv file</a></li>
<li class="chapter" data-level="4.3.2" data-path="working-with-data.html"><a href="working-with-data.html#reading-data-from-r-data-packages"><i class="fa fa-check"></i><b>4.3.2</b> Reading data from R data packages</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="working-with-data.html"><a href="working-with-data.html#summarizing-data"><i class="fa fa-check"></i><b>4.4</b> Summarizing Data</a></li>
<li class="chapter" data-level="4.5" data-path="working-with-data.html"><a href="working-with-data.html#working-with-dplyr"><i class="fa fa-check"></i><b>4.5</b> Working with dplyr</a></li>
<li class="chapter" data-level="4.6" data-path="working-with-data.html"><a href="working-with-data.html#pipes"><i class="fa fa-check"></i><b>4.6</b> Pipes</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="working-with-data.html"><a href="working-with-data.html#the-problem"><i class="fa fa-check"></i><b>4.6.1</b> The problem</a></li>
<li class="chapter" data-level="4.6.2" data-path="working-with-data.html"><a href="working-with-data.html#pipes-1"><i class="fa fa-check"></i><b>4.6.2</b> Pipes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="plotting-1.html"><a href="plotting-1.html"><i class="fa fa-check"></i><b>5</b> Plotting</a>
<ul>
<li class="chapter" data-level="5.1" data-path="plotting-1.html"><a href="plotting-1.html#the-basics-of-ggplot2"><i class="fa fa-check"></i><b>5.1</b> The basics of ggplot2</a></li>
<li class="chapter" data-level="5.2" data-path="plotting-1.html"><a href="plotting-1.html#the-basics-of-ggplot2-1"><i class="fa fa-check"></i><b>5.2</b> The basics of ggplot2</a></li>
<li class="chapter" data-level="5.3" data-path="plotting-1.html"><a href="plotting-1.html#using-lines-in-plots"><i class="fa fa-check"></i><b>5.3</b> Using lines in plots</a></li>
<li class="chapter" data-level="5.4" data-path="plotting-1.html"><a href="plotting-1.html#color-and-fill"><i class="fa fa-check"></i><b>5.4</b> Color and fill</a></li>
<li class="chapter" data-level="5.5" data-path="plotting-1.html"><a href="plotting-1.html#grouping-and-facets"><i class="fa fa-check"></i><b>5.5</b> Grouping and facets</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>6</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#distributions"><i class="fa fa-check"></i><b>6.1</b> Distributions</a></li>
<li class="chapter" data-level="6.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#centraltendency"><i class="fa fa-check"></i><b>6.2</b> Measures of central tendency</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean"><i class="fa fa-check"></i><b>6.2.1</b> The mean</a></li>
<li class="chapter" data-level="6.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#calculating-the-mean-in-r"><i class="fa fa-check"></i><b>6.2.2</b> Calculating the mean in R</a></li>
<li class="chapter" data-level="6.2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median"><i class="fa fa-check"></i><b>6.2.3</b> The median</a></li>
<li class="chapter" data-level="6.2.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean-or-median-whats-the-difference"><i class="fa fa-check"></i><b>6.2.4</b> Mean or median? What’s the difference?</a></li>
<li class="chapter" data-level="6.2.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#trimmedmean"><i class="fa fa-check"></i><b>6.2.5</b> Trimmed mean</a></li>
<li class="chapter" data-level="6.2.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode"><i class="fa fa-check"></i><b>6.2.6</b> Mode</a></li>
<li class="chapter" data-level="6.2.7" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary"><i class="fa fa-check"></i><b>6.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#var"><i class="fa fa-check"></i><b>6.3</b> Measures of variability</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#range"><i class="fa fa-check"></i><b>6.3.1</b> Range</a></li>
<li class="chapter" data-level="6.3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#quantiles-and-percentile"><i class="fa fa-check"></i><b>6.3.2</b> Quantiles and percentile</a></li>
<li class="chapter" data-level="6.3.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#interquartile-range"><i class="fa fa-check"></i><b>6.3.3</b> Interquartile range</a></li>
<li class="chapter" data-level="6.3.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#aad"><i class="fa fa-check"></i><b>6.3.4</b> Mean absolute deviation</a></li>
<li class="chapter" data-level="6.3.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#variance"><i class="fa fa-check"></i><b>6.3.5</b> Variance</a></li>
<li class="chapter" data-level="6.3.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#sd"><i class="fa fa-check"></i><b>6.3.6</b> Standard deviation</a></li>
<li class="chapter" data-level="6.3.7" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#which-measure-to-use"><i class="fa fa-check"></i><b>6.3.7</b> Which measure to use?</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary"><i class="fa fa-check"></i><b>6.4</b> Getting an overall summary of a variable</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summarising-a-vector"><i class="fa fa-check"></i><b>6.4.1</b> Summarising a vector</a></li>
<li class="chapter" data-level="6.4.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summarising-a-data-frame"><i class="fa fa-check"></i><b>6.4.2</b> Summarising a data frame</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#correlations"><i class="fa fa-check"></i><b>6.5</b> Correlations</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">desc_stats</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="descriptive-statistics" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> Descriptive Statistics<a href="descriptive-statistics.html#descriptive-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Anytime you have some data, one of the first tasks you need to do is to find ways to summarize your data neatly. Raw data by itself will not make much sense. So, you want to calculate some summary statistics that describes your data. This is <strong>descriptive statistics</strong> (as opposed to <strong>inferential statistics</strong>).</p>
<p>Let us start with a simple dataset about the mammalian sleep hours.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="descriptive-statistics.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
## ✔ tidyr   1.2.1      ✔ stringr 1.4.1 
## ✔ readr   2.1.2      ✔ forcats 0.5.2 
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="descriptive-statistics.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;magrittr&#39;
## 
## The following object is masked from &#39;package:purrr&#39;:
## 
##     set_names
## 
## The following object is masked from &#39;package:tidyr&#39;:
## 
##     extract</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="descriptive-statistics.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lsr)</span>
<span id="cb5-2"><a href="descriptive-statistics.html#cb5-2" aria-hidden="true" tabindex="-1"></a>mammalian_sleep <span class="ot">&lt;-</span> </span>
<span id="cb5-3"><a href="descriptive-statistics.html#cb5-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">read_csv</span>(<span class="st">&quot;./data/msleep_ggplot2.csv&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-4"><a href="descriptive-statistics.html#cb5-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(name, sleep_total, bodywt) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="descriptive-statistics.html#cb5-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">rename</span>(<span class="at">sleep_total_h =</span> sleep_total, <span class="at">bodywt_kg =</span> bodywt) <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="descriptive-statistics.html#cb5-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">mutate</span>(<span class="at">sleep_total_h =</span> <span class="fu">round</span>(sleep_total_h) )</span></code></pre></div>
<pre><code>## Rows: 83 Columns: 11
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (5): name, genus, vore, order, conservation
## dbl (6): sleep_total, sleep_rem, sleep_cycle, awake, brainwt, bodywt
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="descriptive-statistics.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mammalian_sleep)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   name                       sleep_total_h bodywt_kg
##   &lt;chr&gt;                              &lt;dbl&gt;     &lt;dbl&gt;
## 1 Cheetah                               12    50    
## 2 Owl monkey                            17     0.48 
## 3 Mountain beaver                       14     1.35 
## 4 Greater short-tailed shrew            15     0.019
## 5 Cow                                    4   600    
## 6 Three-toed sloth                      14     3.85</code></pre>
<ul>
<li><p>There are three variables here, <code>name</code>, <code>sleep_total_h</code> and <code>bodywt_kg</code>. For each animal named in <code>name</code>, the <code>sleep_total_h</code> variable contains the average number of hours animals of this kind sleep per day. The variable <code>bodywt_kg</code> contains the average weight of that animal in kg.</p></li>
<li><p>Let’s have a look at the <code>sleep_total_h</code> variable:</p></li>
</ul>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="descriptive-statistics.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mammalian_sleep<span class="sc">$</span>sleep_total_h)</span></code></pre></div>
<pre><code>##  [1] 12 17 14 15  4 14  9  7 10  3  5  9 10 12 10  8  9 17  5 18  4 20  3  3 10
## [26] 11 15 12 10  2  3  6  6  8 10  3 19 10 14 14 13 12 20 15 11  8 14  8  4 10
## [51] 16 10 14  9 10 11 12 14  4  6 11 18  5 13  9 10  8 11 11 17 14 16 13  9  9
## [76] 16  4 16  9  5  6 12 10</code></pre>
<ul>
<li>This output doesn’t make it easy to get a sense of what the data are actually saying. Just “looking at the data” isn’t a terribly effective way of understanding data. In order to get some idea about what’s going on, we need to calculate some descriptive statistics and draw some nice pictures.</li>
</ul>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="descriptive-statistics.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(mammalian_sleep, <span class="fu">aes</span>(sleep_total_h)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="descriptive-statistics.html#cb11-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="dv">1</span>,</span>
<span id="cb11-3"><a href="descriptive-statistics.html#cb11-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> <span class="st">&#39;black&#39;</span>,</span>
<span id="cb11-4"><a href="descriptive-statistics.html#cb11-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">fill =</span> <span class="st">&#39;lightblue&#39;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:histogram1"></span>
<img src="main_files/figure-html/histogram1-1.png" alt="A histogram of the average amount of sleep by animal (the `sleep_total_h` variable). As you might expect, the larger the margin the less frequently you tend to see it." width="672" />
<p class="caption">
Figure 6.1: A histogram of the average amount of sleep by animal (the <code>sleep_total_h</code> variable). As you might expect, the larger the margin the less frequently you tend to see it.
</p>
</div>
<div id="distributions" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Distributions<a href="descriptive-statistics.html#distributions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let us see a couple more data examples to get a sense of what data might look like in the wild. First, let us generate some random data with a <strong>uniform distribution</strong> using the <code>runif()</code> function.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="descriptive-statistics.html#cb12-1" aria-hidden="true" tabindex="-1"></a>uniform <span class="ot">&lt;-</span> <span class="fu">as_tibble_col</span>(<span class="fu">runif</span>(<span class="dv">120</span>, <span class="at">min =</span> <span class="dv">1</span>, <span class="at">max =</span> <span class="dv">6</span>),<span class="at">column_name =</span> <span class="st">&quot;some_value&quot;</span>)</span>
<span id="cb12-2"><a href="descriptive-statistics.html#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="descriptive-statistics.html#cb12-3" aria-hidden="true" tabindex="-1"></a>uniform</span></code></pre></div>
<pre><code>## # A tibble: 120 × 1
##    some_value
##         &lt;dbl&gt;
##  1       2.05
##  2       2.79
##  3       3.75
##  4       3.38
##  5       1.92
##  6       5.02
##  7       5.98
##  8       4.35
##  9       2.27
## 10       1.04
## # … with 110 more rows</code></pre>
<p>Let us plot the uniformly distributed data using a histogram.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="descriptive-statistics.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(uniform, <span class="fu">aes</span>(some_value)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="descriptive-statistics.html#cb14-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.5</span>,<span class="at">boundary=</span><span class="dv">0</span>,</span>
<span id="cb14-3"><a href="descriptive-statistics.html#cb14-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> <span class="st">&#39;black&#39;</span>,</span>
<span id="cb14-4"><a href="descriptive-statistics.html#cb14-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">fill =</span> <span class="st">&#39;lightblue&#39;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:histogram2"></span>
<img src="main_files/figure-html/histogram2-1.png" alt="Histogram of a uniform distribution." width="672" />
<p class="caption">
Figure 6.2: Histogram of a uniform distribution.
</p>
</div>
<p>This looks good but it doesn’t make as much intuitive sense as we’d like. Let us tweak this slightly. Assume that you have a fair dice with 6 sides. So, whenever we roll the dice, each side has an equal probability (i.e. 1/6). Let us simulate this. The data is going to be very similar, except that this time we will need <strong>discrete</strong> values rather than <strong>continuous</strong> values. For that, we need to use the <code>rdunif()</code> function which generates random values with a discrete uniform distribution.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="descriptive-statistics.html#cb15-1" aria-hidden="true" tabindex="-1"></a>uniform <span class="ot">&lt;-</span> <span class="fu">as_tibble_col</span>(<span class="fu">rdunif</span>(<span class="dv">120</span>, <span class="dv">6</span>, <span class="dv">1</span>), <span class="at">column_name=</span><span class="st">&quot;dice_value&quot;</span>)</span>
<span id="cb15-2"><a href="descriptive-statistics.html#cb15-2" aria-hidden="true" tabindex="-1"></a>uniform</span></code></pre></div>
<pre><code>## # A tibble: 120 × 1
##    dice_value
##         &lt;dbl&gt;
##  1          4
##  2          2
##  3          4
##  4          1
##  5          6
##  6          3
##  7          1
##  8          3
##  9          6
## 10          2
## # … with 110 more rows</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="descriptive-statistics.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(uniform, <span class="fu">aes</span>(dice_value)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="descriptive-statistics.html#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">color =</span> <span class="st">&#39;black&#39;</span>,</span>
<span id="cb17-3"><a href="descriptive-statistics.html#cb17-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">fill =</span> <span class="st">&#39;lightblue&#39;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre><code>Just a quick point to think about. Why did we use a histogram for the 
continuous uniform distribution and a bar graph for a discrete one? 
Also, why didn&#39;t we use the **stat=&quot;identity&quot;** argument in the bar graph?</code></pre>
<p>Now, let us generate some random data with a <strong>normal distribution</strong> using the <code>rnorm</code>()` function.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="descriptive-statistics.html#cb19-1" aria-hidden="true" tabindex="-1"></a>normal <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">rnorm</span>(<span class="dv">160</span>))</span></code></pre></div>
<p>Let us plot the normally distributed data using a histogram.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="descriptive-statistics.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(normal, <span class="fu">aes</span>(value)) <span class="sc">+</span></span>
<span id="cb20-2"><a href="descriptive-statistics.html#cb20-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.2</span>,</span>
<span id="cb20-3"><a href="descriptive-statistics.html#cb20-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> <span class="st">&#39;black&#39;</span>,</span>
<span id="cb20-4"><a href="descriptive-statistics.html#cb20-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">fill =</span> <span class="st">&#39;lightblue&#39;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:histogram3"></span>
<img src="main_files/figure-html/histogram3-1.png" alt="Histogram of a normal distribution." width="672" />
<p class="caption">
Figure 6.3: Histogram of a normal distribution.
</p>
</div>
<p>Here’s another one where we provide the <strong>mean</strong> and <strong>standard deviation</strong> parameteres.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="descriptive-statistics.html#cb21-1" aria-hidden="true" tabindex="-1"></a>normal2 <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">rnorm</span>(<span class="dv">160</span>, <span class="at">mean =</span> <span class="dv">8</span>, <span class="at">sd=</span> <span class="fl">0.5</span>))</span></code></pre></div>
<p>Let us plot the seconf normally distributed data using a histogram.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="descriptive-statistics.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(normal2, <span class="fu">aes</span>(value)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="descriptive-statistics.html#cb22-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.2</span>,</span>
<span id="cb22-3"><a href="descriptive-statistics.html#cb22-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> <span class="st">&#39;black&#39;</span>,</span>
<span id="cb22-4"><a href="descriptive-statistics.html#cb22-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">fill =</span> <span class="st">&#39;steelblue&#39;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:histogram4"></span>
<img src="main_files/figure-html/histogram4-1.png" alt="Histogram of a normal distribution." width="672" />
<p class="caption">
Figure 6.4: Histogram of a normal distribution.
</p>
</div>
<p>Finally, let us plot both of the normally distributed data on the same plot to see them side by side.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="descriptive-statistics.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(normal, <span class="fu">aes</span>(value)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="descriptive-statistics.html#cb23-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.2</span>,</span>
<span id="cb23-3"><a href="descriptive-statistics.html#cb23-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> <span class="st">&#39;black&#39;</span>,</span>
<span id="cb23-4"><a href="descriptive-statistics.html#cb23-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">fill =</span> <span class="st">&#39;lightblue&#39;</span>) <span class="sc">+</span></span>
<span id="cb23-5"><a href="descriptive-statistics.html#cb23-5" aria-hidden="true" tabindex="-1"></a>          <span class="fu">geom_histogram</span>(<span class="at">data=</span>normal2, <span class="at">binwidth=</span><span class="fl">0.2</span>,<span class="at">boundary=</span><span class="dv">0</span>,</span>
<span id="cb23-6"><a href="descriptive-statistics.html#cb23-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> <span class="st">&#39;black&#39;</span>,</span>
<span id="cb23-7"><a href="descriptive-statistics.html#cb23-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">fill =</span> <span class="st">&#39;steelblue&#39;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:histogram5"></span>
<img src="main_files/figure-html/histogram5-1.png" alt="Histogram of two normal distributions side by side." width="672" />
<p class="caption">
Figure 6.5: Histogram of two normal distributions side by side.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:normaldatadistributions"></span>
<img src="img/descriptives2/data_distribution.png" alt="Distributions with different means and standard deviations."  />
<p class="caption">
Figure 6.6: Distributions with different means and standard deviations.
</p>
</div>
<div class="figure"><span style="display:block;" id="fig:normalparameterdistributions"></span>
<img src="img/descriptives2/normal_distribution.png" alt="Distributions with different means and standard deviations. The light gray area covers the 68% of the data and the total of the gray areas cover the 95% of the data."  />
<p class="caption">
Figure 6.7: Distributions with different means and standard deviations. The light gray area covers the 68% of the data and the total of the gray areas cover the 95% of the data.
</p>
</div>
</div>
<div id="centraltendency" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Measures of central tendency<a href="descriptive-statistics.html#centraltendency" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Drawing pictures of the data, as I did in Figure <a href="descriptive-statistics.html#fig:histogram1">6.1</a> is an excellent way to convey the “gist” of what the data is trying to tell you, it’s often extremely useful to try to condense the data into a few simple “summary” statistics. In most situations, the first thing that you’ll want to calculate is a measure of <strong><em>central tendency</em></strong>. That is, you’d like to know something about the “average” or “middle” of your data lies. The three most commonly used measures are the <strong>mean</strong>, <strong>median</strong> and <strong>mode</strong>; occasionally people will also report a trimmed mean. I’ll explain each of these in turn, and then discuss when each of them is useful.</p>
<div id="mean" class="section level3 hasAnchor" number="6.2.1">
<h3><span class="header-section-number">6.2.1</span> The mean<a href="descriptive-statistics.html#mean" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>The <strong><em>mean</em></strong> of a set of observations is just a normal, old-fashioned average: add all of the values up, and then divide by the total number of values. The first five animals’ typical amount of sleep is 12 + 17 + 14 + 15 + 4, so the mean of these observations is just:
<span class="math display">\[
\frac{12 + 17 + 14 + 15 + 4}{5} = \frac{62.4}{5} = 12.48
\]</span></p></li>
<li><p>Of course, this definition of the mean isn’t news to anyone: averages (i.e., means) are used so often in everyday life that this is pretty familiar stuff. However, since the concept of a mean is something that everyone already understands, I’ll use this as an excuse to start introducing some of the mathematical notation that statisticians use to describe this calculation, and talk about how the calculations would be done in R.</p></li>
<li><p>The first piece of notation to introduce is <span class="math inline">\(N\)</span>, which we’ll use to refer to the number of observations that we’re averaging (in this case <span class="math inline">\(N = 5\)</span>).</p></li>
<li><p>Next, we need to attach a label to the observations themselves. It’s traditional to use <span class="math inline">\(X\)</span> for this, and to use subscripts to indicate which observation we’re actually talking about.</p></li>
<li><p>That is, we’ll use <span class="math inline">\(X_1\)</span> to refer to the first observation, <span class="math inline">\(X_2\)</span> to refer to the second observation, and so on, all the way up to <span class="math inline">\(X_N\)</span> for the last one. Or, to say the same thing in a slightly more abstract way, we use <span class="math inline">\(X_i\)</span> to refer to the <span class="math inline">\(i\)</span>-th observation. Just to make sure we’re clear on the notation, the following table lists the 5 observations in the <code>sleep_total_h</code> variable, along with the mathematical symbol used to refer to it, and the actual value that the observation corresponds to:</p></li>
</ul>
<!-- to-do: the sleep data isn't great, because it actually consists of averages itself; moreover they are bounded -->
<table>
<thead>
<tr class="header">
<th align="left">the observation</th>
<th align="left">its symbol</th>
<th align="left">the observed value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Cheetah (animal 1)</td>
<td align="left"><span class="math inline">\(X_1\)</span></td>
<td align="left">12 hours</td>
</tr>
<tr class="even">
<td align="left">Owl monkey (animal 2)</td>
<td align="left"><span class="math inline">\(X_2\)</span></td>
<td align="left">17 hours</td>
</tr>
<tr class="odd">
<td align="left">Mountain beaver (animal 3)</td>
<td align="left"><span class="math inline">\(X_3\)</span></td>
<td align="left">14 hours</td>
</tr>
<tr class="even">
<td align="left">Greater short-tailed shrew (animal 4)</td>
<td align="left"><span class="math inline">\(X_4\)</span></td>
<td align="left">15 hours</td>
</tr>
<tr class="odd">
<td align="left">Cow (animal 5)</td>
<td align="left"><span class="math inline">\(X_5\)</span></td>
<td align="left">4 hours</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Okay, now let’s try to write a formula for the mean. By tradition, we use <span class="math inline">\(\bar{X}\)</span> as the notation for the mean. So the calculation for the mean could be expressed using the following formula:
<span class="math display">\[
\bar{X} = \frac{X_1 + X_2 + ... + X_{N-1} + X_N}{N}
\]</span></p></li>
<li><p>This formula is entirely correct, but it’s terribly long, so we make use of the <strong><em>summation symbol</em></strong> <span class="math inline">\(\scriptstyle\sum\)</span> to shorten it.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a> If I want to add up the first five observations, I could write out the sum the long way, <span class="math inline">\(X_1 + X_2 + X_3 + X_4 +X_5\)</span> or I could use the summation symbol to shorten it to this:
<span class="math display">\[
\sum_{i=1}^5 X_i
\]</span></p></li>
<li><p>Taken literally, this could be read as “the sum, taken over all <span class="math inline">\(i\)</span> values from 1 to 5, of the value <span class="math inline">\(X_i\)</span>”. But basically, what it means is “add up the first five observations”. In any case, we can use this notation to write out the formula for the mean, which looks like this:
<span class="math display">\[
\bar{X} = \frac{1}{N} \sum_{i=1}^N X_i
\]</span></p></li>
<li><p>In all honesty, I can’t imagine that all this mathematical notation helps clarify the concept of the mean at all. In fact, it’s really just a fancy way of writing out the same thing I said in words: add all the values up, and then divide by the total number of items. However, that’s not really the reason I went into all that detail.</p></li>
<li><p>My goal was to try to make sure that everyone reading this book is clear on the notation that we’ll be using throughout the book: <span class="math inline">\(\bar{X}\)</span> for the mean, <span class="math inline">\(\scriptstyle\sum\)</span> for the idea of summation, <span class="math inline">\(X_i\)</span> for the <span class="math inline">\(i\)</span>th observation, and <span class="math inline">\(N\)</span> for the total number of observations.</p></li>
<li><p>We’re going to be re-using these symbols a fair bit, so it’s important that you understand them well enough to be able to “read” the equations, and to be able to see that it’s just saying “add up lots of things and then divide by another thing”.</p></li>
</ul>
</div>
<div id="calculating-the-mean-in-r" class="section level3 hasAnchor" number="6.2.2">
<h3><span class="header-section-number">6.2.2</span> Calculating the mean in R<a href="descriptive-statistics.html#calculating-the-mean-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Okay that’s the maths, how do we get the magic computing box to do the work for us? If you really wanted to, you could do this calculation directly in R. For the first numbers, do this just by typing it in as if R were a calculator…</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="descriptive-statistics.html#cb24-1" aria-hidden="true" tabindex="-1"></a>(<span class="dv">12</span> <span class="sc">+</span> <span class="dv">17</span> <span class="sc">+</span> <span class="dv">14</span> <span class="sc">+</span> <span class="dv">15</span> <span class="sc">+</span> <span class="dv">4</span>) <span class="sc">/</span> <span class="dv">5</span></span></code></pre></div>
<pre><code>## [1] 12.4</code></pre>
<p>… in which case R outputs the answer 12.4, just as if it were a calculator.</p>
<ul>
<li>However, we learned quicker ways of doing that</li>
</ul>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="descriptive-statistics.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>( mammalian_sleep<span class="sc">$</span>sleep_total_h[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] )<span class="sc">/</span> <span class="dv">5</span></span></code></pre></div>
<pre><code>## [1] 12.4</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="descriptive-statistics.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or:</span></span>
<span id="cb28-2"><a href="descriptive-statistics.html#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>( mammalian_sleep<span class="sc">$</span>sleep_total_h[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>] )</span></code></pre></div>
<pre><code>## [1] 12.4</code></pre>
</div>
<div id="median" class="section level3 hasAnchor" number="6.2.3">
<h3><span class="header-section-number">6.2.3</span> The median<a href="descriptive-statistics.html#median" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>The second measure of central tendency that people use a lot is the <strong><em>median</em></strong>, and it’s even easier to describe than the mean. The median of a set of observations is just the middle value.</p></li>
<li><p>As before let’s imagine we were interested only in the first 5 animals: They sleep 12, 17, 14, 15, and 4 hours respectively. To figure out the median, we sort these numbers into ascending order:
<span class="math display">\[
4, 12, \color{red}{14}, 15, 17
\]</span></p></li>
<li><p>From inspection, it’s obvious that the median value of these 5 observations is 14, since that’s the middle one in the sorted list (I’ve put it in red to make it even more obvious). Easy stuff.</p></li>
<li><p>But what should we do if we were interested in the first 6 animals rather than the first 5? Since the sixth animal sleeps for 14 hours, our sorted list is now:
<span class="math display">\[
4, 12, \color{red}{14}, \color{red}{14}, 15, 17
\]</span></p></li>
<li><p>That’s also easy. It’s still 14.</p></li>
<li><p>But what we do if we were interested in the first 8 animals? Here is our new sorted list.
<span class="math display">\[
4,  7,  9, \color{red}{12}, \color{red}{14}, 14, 15, 17
\]</span></p></li>
<li><p>There are now <em>two</em> middle numbers, 12 and 14. The median is defined as the average of those two numbers, which is of course 13.</p></li>
<li><p>To understand why, think of the median as the value that divides the sorted list of numbers into two halves – those on its left, and those on its right.</p></li>
<li><p>As before, it’s very tedious to do this by hand when you’ve got lots of numbers. To illustrate this, here’s what happens when you use R to sort all the sleep durations. First, I’ll use the <code>sort()</code> function to display the 83 numbers in increasing numerical order:</p></li>
</ul>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="descriptive-statistics.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>( mammalian_sleep<span class="sc">$</span>sleep_total_h )</span></code></pre></div>
<pre><code>##  [1]  2  3  3  3  3  3  4  4  4  4  4  5  5  5  5  6  6  6  6  7  8  8  8  8  8
## [26]  9  9  9  9  9  9  9  9 10 10 10 10 10 10 10 10 10 10 10 10 11 11 11 11 11
## [51] 11 12 12 12 12 12 12 13 13 13 14 14 14 14 14 14 14 14 15 15 15 16 16 16 16
## [76] 17 17 17 18 18 19 20 20</code></pre>
<ul>
<li>Because the vector is 83 elements long, the middle value is at position 42. This means that the median of this vector is 10. In real life, of course, no-one actually calculates the median by sorting the data and then looking for the middle value. In real life, we use the median command:</li>
</ul>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="descriptive-statistics.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>( mammalian_sleep<span class="sc">$</span>sleep_total_h )</span></code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>which outputs the median value of 10.</p>
</div>
<div id="mean-or-median-whats-the-difference" class="section level3 hasAnchor" number="6.2.4">
<h3><span class="header-section-number">6.2.4</span> Mean or median? What’s the difference?<a href="descriptive-statistics.html#mean-or-median-whats-the-difference" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="figure"><span style="display:block;" id="fig:meanmedian"></span>
<img src="img/descriptives2/meanmedian.png" alt="An illustration of the difference between how the mean and the median should be interpreted. The mean is basically the &quot;centre of gravity&quot; of the data set: if you imagine that the histogram of the data is a solid object, then the point on which you could balance it (as if on a see-saw) is the mean. In contrast, the median is the middle observation. Half of the observations are smaller, and half of the observations are larger."  />
<p class="caption">
Figure 6.8: An illustration of the difference between how the mean and the median should be interpreted. The mean is basically the “centre of gravity” of the data set: if you imagine that the histogram of the data is a solid object, then the point on which you could balance it (as if on a see-saw) is the mean. In contrast, the median is the middle observation. Half of the observations are smaller, and half of the observations are larger.
</p>
</div>
<ul>
<li><p>Knowing how to calculate means and medians is only a part of the story. You also need to understand what each one is saying about the data, and what that implies for when you should use each one. This is illustrated in Figure <a href="descriptive-statistics.html#fig:meanmedian">6.8</a> the mean is kind of like the “centre of gravity” of the data set, whereas the median is the “middle value” in the data. What this implies, as far as which one you should use, depends a little on what type of data you’ve got and what you’re trying to achieve. As a rough guide:</p></li>
<li><p>One consequence is that there’s systematic differences between the mean and the median when the histogram is asymmetric (skewed; see Section <a href="#skewandkurtosis"><strong>??</strong></a>). This is illustrated in Figure <a href="descriptive-statistics.html#fig:meanmedian">6.8</a> notice that the median (right hand side) is located closer to the “body” of the histogram, whereas the mean (left hand side) gets dragged towards the “tail” (where the extreme values are).</p></li>
<li><p>To give a concrete example, suppose Bob (income $50,000), Kate (income $60,000) and Jane (income $65,000) are sitting at a table: the average income at the table is $58,333 and the median income is $60,000. Then Bill sits down with them (income $100,000,000). The average income has now jumped to $25,043,750 but the median rises only to $62,500. If you’re interested in looking at the overall income at the table, the mean might be the right answer; but if you’re interested in what counts as a typical income at the table, the median would be a better choice here.</p></li>
</ul>
<div class="figure"><span style="display:block;" id="fig:meanmedian2"></span>
<img src="img/descriptives2/mean_median.png" alt="Another example of mean and median where mean is moved by the outliers but median is constant."  />
<p class="caption">
Figure 6.9: Another example of mean and median where mean is moved by the outliers but median is constant.
</p>
</div>
<!--
### A real life example{#housingpriceexample}
- Income example
-->
</div>
<div id="trimmedmean" class="section level3 hasAnchor" number="6.2.5">
<h3><span class="header-section-number">6.2.5</span> Trimmed mean<a href="descriptive-statistics.html#trimmedmean" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>One of the fundamental rules of applied statistics is that the data are messy. Real life is never simple, and so the data sets that you obtain are never as straightforward as the statistical theory says.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> This can have awkward consequences. To illustrate, consider this rather strange looking data set (nevermind what it represents):
<span class="math display">\[
-100,2,3,4,5,6,7,8,9,10
\]</span></p></li>
<li><p>If you were to observe this in a real life data set, you’d probably suspect that something funny was going on with the <span class="math inline">\(-100\)</span> value. It’s probably an <strong><em>outlier</em></strong>, a value that doesn’t really belong with the others. You might consider removing it from the data set entirely, and in this particular case I’d probably agree with that course of action.</p></li>
<li><p>In real life, however, you don’t always get such cut-and-dried examples. For instance, you might get this instead:
<span class="math display">\[
-15,2,3,4,5,6,7,8,9,12
\]</span></p></li>
<li><p>The <span class="math inline">\(-15\)</span> looks a bit suspicious, but not anywhere near as much as that <span class="math inline">\(-100\)</span> did. In this case, it’s a little trickier. It <em>might</em> be a legitimate observation, it might not.</p></li>
<li><p>When faced with a situation where some of the most extreme-valued observations might not be quite trustworthy, the mean is not necessarily a good measure of central tendency. It is highly sensitive to one or two extreme values, and is thus not considered to be a <strong><em>robust</em></strong> measure.</p></li>
<li><p>One remedy that we’ve seen is to use the median. A more general solution is to use a “trimmed mean”. To calculate a trimmed mean, what you do is “discard” the most extreme examples on both ends (i.e., the largest and the smallest), and then take the mean of everything else. The goal is to preserve the best characteristics of the mean and the median:</p>
<ul>
<li>just like a median, you aren’t highly influenced by extreme outliers, but …</li>
<li>like the mean, you “use” more than one of the observations.</li>
</ul></li>
<li><p>Generally, we describe a trimmed mean in terms of the percentage of observation on either side that are discarded. So, for instance, a 10% trimmed mean discards the largest 10% of the observations <em>and</em> the smallest 10% of the observations, and then takes the mean of the remaining 80% of the observations.</p></li>
<li><p>Not surprisingly, the 0% trimmed mean is just the regular mean, and the 50% trimmed mean is the median. In that sense, trimmed means provide a whole family of central tendency measures that span the range from the mean to the median.</p></li>
<li><p>For our toy example above, we have 10 observations, and so a 10% trimmed mean is calculated by ignoring the largest value (i.e., <code>12</code>) and the smallest value (i.e., <code>-15</code>) and taking the mean of the remaining values. First, let’s enter the data</p></li>
</ul>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="descriptive-statistics.html#cb34-1" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">c</span>( <span class="sc">-</span><span class="dv">15</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">12</span> )</span></code></pre></div>
<p>Next, let’s calculate means and medians:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="descriptive-statistics.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>( dataset )</span></code></pre></div>
<pre><code>## [1] 4.1</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="descriptive-statistics.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>( dataset )</span></code></pre></div>
<pre><code>## [1] 5.5</code></pre>
<ul>
<li>That’s a fairly substantial difference, but I’m tempted to think that the mean is being influenced a bit too much by the extreme values at either end of the data set, especially the <span class="math inline">\(-15\)</span> one. So let’s just try trimming the mean a bit. If I take a 10% trimmed mean, we’ll drop the extreme values on either side, and take the mean of the rest:</li>
</ul>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="descriptive-statistics.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>( dataset, <span class="at">trim =</span> .<span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 5.5</code></pre>
<ul>
<li>In this case it gives exactly the same answer as the median. Note that, to get a 10% trimmed mean you write <code>trim = .1</code>, not <code>trim = 10</code>.</li>
</ul>
</div>
<div id="mode" class="section level3 hasAnchor" number="6.2.6">
<h3><span class="header-section-number">6.2.6</span> Mode<a href="descriptive-statistics.html#mode" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>The <strong><em>mode</em></strong> is the last measure of central tendency we’ll look at. It is very simple: it is the value that occurs most frequently.</p></li>
<li><p>Let’s look at the some soccer data: specifically, the European Cup and Champions League results in the time from 1955-2016.</p></li>
<li><p>Lets find out which team has won the most matches. The command below tells R we just want the first 25 rows of the data.frame.</p></li>
</ul>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="descriptive-statistics.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(engsoccerdata)</span>
<span id="cb41-2"><a href="descriptive-statistics.html#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="descriptive-statistics.html#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(champs<span class="sc">$</span>tiewinner) <span class="sc">%&gt;%</span> <span class="fu">sort</span>(<span class="at">decreasing=</span>T) <span class="sc">%&gt;%</span> .[<span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>]</span></code></pre></div>
<pre><code>## 
##       Real Madrid     Bayern Munich        SL Benfica          AC Milan 
##               183               134               110               103 
##         Barcelona         Liverpool          Juventus       Dinamo Kiev 
##               101                97                87                82 
##            Celtic Manchester United    RSC Anderlecht          AFC Ajax 
##                81                81                75                71 
##    Internazionale  Steaua Bucuresti     Crvena Zvezda           Rangers 
##                66                63                61                58 
## Partizan Belgrade     PSV Eindhoven     Dinamo Zagreb          FC Porto 
##                52                49                48                46 
##   Atletico Madrid     Panathinaikos      BATE Borisov        CSKA Sofia 
##                45                44                40                40 
##       Galatasaray 
##                40</code></pre>
<ul>
<li><p>It appears that the mode of the winning team is ‘Real Madrid’.</p></li>
<li><p>Of course, the mode is the right (and only) summary for nominal variables.</p></li>
<li><p>But we can compute a mode for all types of variables. For example, let’s take a look at the mean, median, and mode of the total number of goals per game.</p></li>
</ul>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="descriptive-statistics.html#cb43-1" aria-hidden="true" tabindex="-1"></a>champs <span class="sc">%&lt;&gt;%</span> <span class="fu">mutate</span>(<span class="at">total_goals =</span> hgoal <span class="sc">+</span> vgoal) <span class="co"># total goals is home team goals + visitor goals</span></span></code></pre></div>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="descriptive-statistics.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(champs<span class="sc">$</span>total_goals)</span></code></pre></div>
<pre><code>## [1] 2.81642</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="descriptive-statistics.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(champs<span class="sc">$</span>total_goals)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="descriptive-statistics.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modeOf</span>(champs<span class="sc">$</span>total_goals)</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="descriptive-statistics.html#cb50-1" aria-hidden="true" tabindex="-1"></a>mean_goals <span class="ot">&lt;-</span> <span class="fu">mean</span>(champs<span class="sc">$</span>total_goals)</span>
<span id="cb50-2"><a href="descriptive-statistics.html#cb50-2" aria-hidden="true" tabindex="-1"></a>median_goals <span class="ot">&lt;-</span> <span class="fu">median</span>(champs<span class="sc">$</span>total_goals)</span>
<span id="cb50-3"><a href="descriptive-statistics.html#cb50-3" aria-hidden="true" tabindex="-1"></a>mode_goals <span class="ot">&lt;-</span> <span class="fu">modeOf</span>(champs<span class="sc">$</span>total_goals)</span>
<span id="cb50-4"><a href="descriptive-statistics.html#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="descriptive-statistics.html#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(champs, <span class="fu">aes</span>(total_goals)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">fill=</span> <span class="st">&#39;dimgrey&#39;</span>) <span class="sc">+</span> </span>
<span id="cb50-6"><a href="descriptive-statistics.html#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mean_goals, <span class="at">color =</span> <span class="st">&quot;indianred&quot;</span>) <span class="sc">+</span> </span>
<span id="cb50-7"><a href="descriptive-statistics.html#cb50-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> median_goals, <span class="at">color =</span> <span class="st">&quot;steelblue&quot;</span>) <span class="sc">+</span> </span>
<span id="cb50-8"><a href="descriptive-statistics.html#cb50-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mode_goals, <span class="at">color =</span> <span class="st">&quot;yellowgreen&quot;</span>) <span class="sc">+</span> </span>
<span id="cb50-9"><a href="descriptive-statistics.html#cb50-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="at">data=</span><span class="cn">NULL</span>, <span class="at">x =</span> mean_goals<span class="fl">-.6</span>, <span class="at">y=</span><span class="dv">1470</span>, <span class="at">label =</span> <span class="st">&quot;mean&quot;</span>, <span class="at">color =</span> <span class="st">&quot;indianred&quot;</span>) <span class="sc">+</span></span>
<span id="cb50-10"><a href="descriptive-statistics.html#cb50-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="at">data=</span><span class="cn">NULL</span>, <span class="at">x =</span> median_goals<span class="fl">+.75</span>, <span class="at">y=</span><span class="dv">1500</span>, <span class="at">label =</span> <span class="st">&quot;median&quot;</span>, <span class="at">color =</span> <span class="st">&quot;steelblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb50-11"><a href="descriptive-statistics.html#cb50-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text</span>(<span class="at">data=</span><span class="cn">NULL</span>, <span class="at">x =</span> mode_goals<span class="fl">-.6</span>, <span class="at">y=</span><span class="dv">1530</span>, <span class="at">label =</span> <span class="st">&quot;mode&quot;</span>, <span class="at">color =</span> <span class="st">&quot;yellowgreen&quot;</span>)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="main_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
</div>
<div id="summary" class="section level3 hasAnchor" number="6.2.7">
<h3><span class="header-section-number">6.2.7</span> Summary<a href="descriptive-statistics.html#summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>There are multiple measures of central tendency that can be used to summarize an aspect of a distribution: <strong>_ (arithmetic) mean, median, and mode_</strong>.</li>
<li>They answer different questions about distribution. For example, in the distribution of number of goals per game in the previous section
<ul>
<li>mean: “If the same number of goals were scored in each game, how many goals would be scored?”</li>
<li>median: “What is a ‘mediocre’ game like?”</li>
<li>mode: “What is the most typical game like?”
<!--
mean: "If all the income were redistributed equally among the households, how much would each household make?"
median: "What is the income of the middle household?"
mode: "If we choose a household at random, what is its income most likely to be?"
trimmed mean: "What is the mean income of those who have work? (i.e., how much *can* one expect to earn *if* one finds a job)"
--></li>
</ul></li>
</ul>
</div>
</div>
<div id="var" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Measures of variability<a href="descriptive-statistics.html#var" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>The statistics that we’ve discussed so far all relate to <em>central tendency</em>. That is, they all talk about which values are “in the middle” or “popular” in the data.</li>
<li>The second thing that we really want is a measure of the <strong><em>variability</em></strong> of the data.
<ul>
<li>That is, how “spread out” are the data?</li>
<li>In other words, how ‘representative’ is our measure of central tendency of most data points.</li>
</ul></li>
<li>Let’s consider interval and ratio scale data.</li>
</ul>
<div id="range" class="section level3 hasAnchor" number="6.3.1">
<h3><span class="header-section-number">6.3.1</span> Range<a href="descriptive-statistics.html#range" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>The <strong><em>range</em></strong> of a variable is very simple: it’s the biggest value minus the smallest value. For the sleep data, the maximum value is 20, and the minimum value is 2. We can calculate these values in R using the <code>max()</code> and <code>min()</code> functions:</li>
</ul>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="descriptive-statistics.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>( mammalian_sleep<span class="sc">$</span>sleep_total_h )</span></code></pre></div>
<pre><code>## [1] 20</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="descriptive-statistics.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>( mammalian_sleep<span class="sc">$</span>sleep_total_h )</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>where I’ve omitted the output because it’s not interesting.</p>
<ul>
<li>The other possibility is to use the <code>range()</code> function; which outputs both the minimum value and the maximum value in a vector, like this:</li>
</ul>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="descriptive-statistics.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>( mammalian_sleep<span class="sc">$</span>sleep_total_h )</span></code></pre></div>
<pre><code>## [1]  2 20</code></pre>
<ul>
<li>Although the range is the simplest way to quantify the notion of “variability”, it’s one of the worst. Recall from our discussion of the mean that we want our summary measure to be robust. If the data set has one or two extremely bad values in it, we’d like our statistics not to be unduly influenced by these cases. If we look once again at our toy example of a data set containing very extreme outliers…
<span class="math display">\[
-100,2,3,4,5,6,7,8,9,10
\]</span>
… it is clear that the range is not robust, since this has a range of 110, but if the outlier were removed we would have a range of only 8.</li>
</ul>
</div>
<div id="quantiles-and-percentile" class="section level3 hasAnchor" number="6.3.2">
<h3><span class="header-section-number">6.3.2</span> Quantiles and percentile<a href="descriptive-statistics.html#quantiles-and-percentile" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>A key concept we will need to build on to conceptualize several other measures of variability are <strong><em>quantiles</em></strong> or <strong><em>percentiles</em></strong>.</p></li>
<li><p>A <strong><em>percentile</em></strong> is the smallest value in a dataset such that a set percentage is smaller than it. (A <strong><em>quantile</em></strong> does pretty much the same but is more generic.)</p></li>
<li><p>For example, if the 10-th percentile (i.e., the <span class="math inline">\(0.1\)</span> quantile) of a list of values is 73, this means that 10 percent of the values are smaller than or equal to 73.</p></li>
<li><p>Let’s take a look at the 20 shortest sorted sleep durations and determine the 10-th percentile (<span class="math inline">\(0.1\)</span> quantile), 30-th percentile (<span class="math inline">\(0.3\)</span> quantile), 50-th percentile (<span class="math inline">\(0.5\)</span> quantile), and the 90-th percentile (<span class="math inline">\(0.9\)</span> quantile).</p></li>
<li><p>Here are the values:</p></li>
</ul>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="descriptive-statistics.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(mammalian_sleep<span class="sc">$</span>sleep_total_h)[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>]</span></code></pre></div>
<pre><code>##  [1] 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 6 6 6 6 7</code></pre>
<ul>
<li>And here is a sorted plot of the 20 smallest values:</li>
</ul>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="descriptive-statistics.html#cb60-1" aria-hidden="true" tabindex="-1"></a>quantile <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.1</span>,<span class="fl">0.3</span>,<span class="fl">0.5</span>,<span class="fl">0.9</span>)</span>
<span id="cb60-2"><a href="descriptive-statistics.html#cb60-2" aria-hidden="true" tabindex="-1"></a>quantile_points <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.1</span>,<span class="fl">0.3</span>,<span class="fl">0.5</span>,<span class="fl">0.9</span>)<span class="sc">*</span><span class="dv">20</span></span>
<span id="cb60-3"><a href="descriptive-statistics.html#cb60-3" aria-hidden="true" tabindex="-1"></a>quantile_labels <span class="ot">&lt;-</span> <span class="fu">sprintf</span>(<span class="st">&quot;%0.1f quantile</span><span class="sc">\n</span><span class="st">(point %d of 20)&quot;</span>, quantile, quantile_points)</span>
<span id="cb60-4"><a href="descriptive-statistics.html#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="cn">NULL</span>, <span class="fu">aes</span>(<span class="at">x=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>, <span class="at">y=</span><span class="fu">sort</span>(mammalian_sleep<span class="sc">$</span>sleep_total_h)[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>])) <span class="sc">+</span></span>
<span id="cb60-5"><a href="descriptive-statistics.html#cb60-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb60-6"><a href="descriptive-statistics.html#cb60-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> quantile_points) <span class="sc">+</span></span>
<span id="cb60-7"><a href="descriptive-statistics.html#cb60-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_label</span>(<span class="fu">aes</span>(<span class="at">x=</span>quantile_points, <span class="at">y=</span><span class="fl">6.5</span>, <span class="at">label=</span>quantile_labels )) <span class="sc">+</span></span>
<span id="cb60-8"><a href="descriptive-statistics.html#cb60-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Position in ordered vector&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Sleep (hours)&quot;</span>)</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<ul>
<li>As you can see:
<ul>
<li>10-th percentile (<span class="math inline">\(0.1\)</span> quantile): 3 [to be found at position 2, since 2 data points constitute 10 percent of the data]</li>
<li>30-th percentile (<span class="math inline">\(0.3\)</span> quantile): 3 [to be found at position 6, since 6 data points constitute 30 percent of the data]</li>
<li>50-th percentile (<span class="math inline">\(0.5\)</span> quantile): 4 [to be found at position 10, since 10 data points constitute 50 percent of the data]</li>
<li>90-th percentile (<span class="math inline">\(0.9\)</span> quantile): 6 [to be found at position 18, since 18 data points constitute 90 percent of the data]</li>
</ul></li>
<li>The 50-th percentile is the median.</li>
</ul>
</div>
<div id="interquartile-range" class="section level3 hasAnchor" number="6.3.3">
<h3><span class="header-section-number">6.3.3</span> Interquartile range<a href="descriptive-statistics.html#interquartile-range" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>The <strong><em>interquartile range</em></strong> (IQR) is like the range, but instead of calculating the difference between the biggest and smallest value, it calculates the difference between the 25th quantile and the 75th quantile.</li>
<li>R provides you with a way of calculating quantiles, using the (surprise, surprise) <code>quantile()</code> function. Let’s use it to calculate the median sleep durations:</li>
</ul>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="descriptive-statistics.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>( <span class="at">x =</span> mammalian_sleep<span class="sc">$</span>sleep_total_h, <span class="at">probs =</span> .<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## 50% 
##  10</code></pre>
<ul>
<li>And not surprisingly, this agrees with the answer that we saw earlier with the <code>median()</code> function. Now, we can actually input lots of quantiles at once, by specifying a vector for the <code>probs</code> argument. So lets do that, and get the 25th and 75th percentile:</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="descriptive-statistics.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>( <span class="at">x =</span> mammalian_sleep<span class="sc">$</span>sleep_total_h, <span class="at">probs =</span> <span class="fu">c</span>(.<span class="dv">25</span>,.<span class="dv">75</span>) )</span></code></pre></div>
<pre><code>## 25% 75% 
##   8  14</code></pre>
<ul>
<li>And, by noting that <span class="math inline">\(14 - 8 = 6\)</span>, we can see that the interquartile range for the sleep durations is 6. Of course, that seems like too much work to do all that typing, so R has a built in function called <code>IQR()</code> that we can use:</li>
</ul>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="descriptive-statistics.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">IQR</span>( <span class="at">x =</span> mammalian_sleep<span class="sc">$</span>sleep_total_h )</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<ul>
<li><p>While it’s obvious how to interpret the range, it’s a little less obvious how to interpret the IQR. The simplest way to think about it is like this: the interquartile range is the range spanned by the “middle half” of the data. That is, one quarter of the data falls below the 25th percentile, one quarter of the data is above the 75th percentile, leaving the “middle half” of the data lying in between the two. And the IQR is the range covered by that middle half.</p></li>
<li><p>IQR is used to identify the outliers (i.e. extreme values). Any value above <code>Q3 + IQR *1.5</code> or below <code>Q1 - IQR*1.5</code> is considered to be an outlier.</p></li>
</ul>
</div>
<div id="aad" class="section level3 hasAnchor" number="6.3.4">
<h3><span class="header-section-number">6.3.4</span> Mean absolute deviation<a href="descriptive-statistics.html#aad" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>The range and the interquartile range, both rely on the idea that we can measure the spread of the data by looking at the quantiles of the data.</p></li>
<li><p>However, this isn’t the only way to think about the problem. A different approach is to select a meaningful reference point (usually the mean or the median) and then report the <strong><em>“typical” deviations</em></strong> from that reference point.
<!--
- What do we mean by "typical" deviation? Usually, the mean or median value of these deviations! In practice, this leads to two different measures, the "mean absolute deviation (from the mean)" and the "median absolute deviation (from the median)". From what I've read, the measure based on the median seems to be used in statistics, and does seem to be the better of the two, but to be honest I don't think I've seen it used much in psychology. The measure based on the mean does occasionally show up in psychology though. In this section I'll talk about the first one, and I'll come back to talk about the second one later.
--></p></li>
<li><p>Let’s go through the <strong><em>mean absolute deviation</em></strong> (AAD for average absolute deviation, since MAD is reserved for the median absolute deviation) from the mean a little more slowly. One useful thing about this measure is that the name actually tells you exactly how to calculate it:
<span class="math display">\[
AAD(X) = \frac{1}{N} \sum_{i = 1}^N |X_i - \bar{X}|
\]</span></p></li>
<li><p>Let’s compute the AAD for the first data points in the sleep data:
<span class="math display">\[
12, 17, 14, 15, 4
\]</span></p></li>
<li><p>The mean of the dataset is 12.4. That is, <span class="math inline">\(\bar{X} = 12.4\)</span></p></li>
<li><p>The deviations <span class="math inline">\(X_i - \bar{X}\)</span> are:
<span class="math display">\[
-0.4, 4.6, 1.6, 2.6, -8.4
\]</span></p></li>
<li><p>The absolute deviations <span class="math inline">\(|X_i - \bar{X}|\)</span> are:
<span class="math display">\[
0.4, 4.6, 1.6, 2.6, 8.4
\]</span></p></li>
<li><p>The sum of the absolute deviations <span class="math inline">\(\sum_{i = 1}^N |X_i - \bar{X}|\)</span> is 17.6.</p></li>
<li><p>And <span class="math inline">\(N=5\)</span>, which means, that, in our case: <span class="math inline">\(AAD(X) = \frac{1}{N} \sum_{i = 1}^N |X_i - \bar{X}| = 3.52\)</span></p></li>
<li><p>In R, we can compute it for the entire vector.</p></li>
</ul>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="descriptive-statistics.html#cb67-1" aria-hidden="true" tabindex="-1"></a>mean_sleep <span class="ot">&lt;-</span> <span class="fu">mean</span>(mammalian_sleep<span class="sc">$</span>sleep_total_h)</span>
<span id="cb67-2"><a href="descriptive-statistics.html#cb67-2" aria-hidden="true" tabindex="-1"></a>deviation_sleep <span class="ot">&lt;-</span> mean_sleep <span class="sc">-</span> mammalian_sleep<span class="sc">$</span>sleep_total_h</span>
<span id="cb67-3"><a href="descriptive-statistics.html#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>( <span class="fu">abs</span>(deviation_sleep) )</span></code></pre></div>
<pre><code>## [1] 3.576717</code></pre>
<ul>
<li>An alternative, more compact way to write it is using (lots) pipes:</li>
</ul>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="descriptive-statistics.html#cb69-1" aria-hidden="true" tabindex="-1"></a>mammalian_sleep<span class="sc">$</span>sleep_total_h <span class="sc">%&gt;%</span> <span class="fu">subtract</span>(., <span class="fu">mean</span>(.)) <span class="sc">%&gt;%</span> <span class="fu">abs</span>() <span class="sc">%&gt;%</span> <span class="fu">mean</span>()</span></code></pre></div>
<pre><code>## [1] 3.576717</code></pre>
<ul>
<li>The interpretation of the AAD is quite straightforward: It is the average distance from the average. When it’s big, the values are quite spread out. When it’s small, they are close. The units are the same (hours in our case).</li>
</ul>
<!--
and once again we'll start by pretending that there's only 5 games in total, with winning margins of 56, 31, 56, 8 and 32. Since our calculations rely on an examination of the deviation from some reference point (in this case the mean), the first thing we need to calculate is the mean, $\bar{X}$. For these five observations, our mean is $\bar{X} = 36.6$. The next step is to convert each of our observations $X_i$ into a deviation score.

We do this by calculating the difference between the observation $X_i$ and the mean $\bar{X}$. That is, the deviation score is defined to be $X_i - \bar{X}$. For the first observation in our sample, this is equal to $56 - 36.6 = 19.4$. Okay, that's simple enough. The next step in the process is to convert these deviations to absolute deviations. As we discussed earlier when talking about  the `abs()` function in R (Section \@ref(usingfunctions)), we do this by converting any negative values to positive ones. Mathematically, we would denote the absolute value of $-3$ as $|-3|$, and so we say that $|-3| = 3$. We use the absolute value function here because we don't really care whether the value is higher than the mean or lower than the mean, we're just interested in how *close* it is to the mean. To help make this process as obvious as possible, the table below shows these calculations for all five observations:




|the observation        |its symbol |the observed value |
|:----------------------|:----------|:------------------|
|winning margin, game 1 |$X_1$      |56 points          |
|winning margin, game 2 |$X_2$      |31 points          |
|winning margin, game 3 |$X_3$      |56 points          |
|winning margin, game 4 |$X_4$      |8 points           |
|winning margin, game 5 |$X_5$      |32 points          |

Now that we have calculated the absolute deviation score for every observation in the data set, all that we have to do to calculate the mean of these scores. Let's do that:
$$
\frac{19.4 + 5.6 + 19.4 + 28.6 + 4.6}{5} = 15.52
$$
And we're done. The mean absolute deviation for these five scores is 15.52.

However, while our calculations for this little example are at an end, we do have a couple of things left to talk about. Firstly, we should really try to write down a proper mathematical formula. But in order do to this I need some mathematical notation to refer to the mean absolute deviation. Irritatingly, "mean absolute deviation" and "median absolute deviation" have the same acronym (MAD), which leads to a certain amount of ambiguity, and since R tends to use MAD to refer to the median absolute deviation, I'd better come up with something different for the mean absolute deviation. Sigh. What I'll do is use AAD instead, short for *average* absolute deviation. Now that we have some unambiguous notation, here's the formula that describes what we just calculated:
$$
\mbox{}(X) = \frac{1}{N} \sum_{i = 1}^N |X_i - \bar{X}|
$$

The last thing we need to talk about is how to calculate AAD in R. One possibility would be to do everything using low level commands, laboriously following the same steps that I used when describing the calculations above. However, that's pretty tedious. You'd end up with a series of commands that might look like this:

```r
X <- c(56, 31,56,8,32)   # enter the data
X.bar <- mean( X )       # step 1. the mean of the data
AD <- abs( X - X.bar )   # step 2. the absolute deviations from the mean
AAD <- mean( AD )        # step 3. the mean absolute deviations
print( AAD )             # print the results
```

```
## [1] 15.52
```

Each of those commands is pretty simple, but there's just too many of them. And because I find that to be too much typing, the `lsr` package has a very simple function called `aad()` that does the calculations for you. If we apply the `aad()` function to our data, we get this:

```r
library(lsr)
aad( X )
```

```
## [1] 15.52
```
No suprises there.
-->
</div>
<div id="variance" class="section level3 hasAnchor" number="6.3.5">
<h3><span class="header-section-number">6.3.5</span> Variance<a href="descriptive-statistics.html#variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>Although the mean absolute deviation measure has its uses, it’s not the best measure of variability to use.</p></li>
<li><p>For a number of practical reasons, there are some solid reasons to prefer squared deviations rather than absolute deviations. A measure of variability based on <em>squared deviations</em> has a number of useful properties in <em>inferential statistics</em> and <em>statistical modeling</em>.<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a></p></li>
<li><p>If we do that, we obtain a measure is called the <strong><em>variance</em></strong>, which for a specific set of observations <span class="math inline">\(X\)</span> is written <span class="math inline">\(\mbox{s}_X^2\)</span>. It is the most wide-spread measure of variability because it is a key concept in <em>inferential statistics</em>.</p></li>
<li><p>The formula that we use to calculate the variance of a set of observations is as follows:
<span class="math display">\[
\mbox{s}_X^2 = \frac{1}{N-1} \sum_{i=1}^N \left( X_i - \bar{X} \right)^2
\]</span></p></li>
<li><p>As you can see, it’s basically the same formula that we used to calculate the mean absolute deviation, except that:</p>
<ol style="list-style-type: decimal">
<li>Instead of using “absolute deviations” we use “squared deviations”.</li>
<li>Instead of dividing by <span class="math inline">\(N\)</span> (which gives us the average deviation), we divide by <span class="math inline">\(N-1\)</span> (which gives us <em>‘sort-of-the-average’</em>). [We will talk about this in a little while.]</li>
</ol></li>
</ul>
<!--
  . It is for this reason that the variance is sometimes referred to as the "mean square deviation".
-->
<ul>
<li>Now that we’ve got the basic idea, let’s have a look at a concrete example. Once again, let’s use the first five sleep durations. If we follow the same approach that we took last time, we end up with the following table:</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-33">Table 6.1: </span>Regular, abssolute, and squared deviations</caption>
<colgroup>
<col width="15%" />
<col width="10%" />
<col width="11%" />
<col width="30%" />
<col width="32%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Notation [English]</th>
<th align="left"><span class="math inline">\(i\)</span> [animal]</th>
<th align="left"><span class="math inline">\(X_i\)</span> [value]</th>
<th align="left"><span class="math inline">\(X_i - \bar{X}\)</span> [deviation from mean]</th>
<th align="left"><span class="math inline">\((X_i - \bar{X})^2\)</span> [squared deviation]</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="left">1</td>
<td align="left">12</td>
<td align="left">-0.4</td>
<td align="left">0.16</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">2</td>
<td align="left">17</td>
<td align="left">4.6</td>
<td align="left">21.16</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">3</td>
<td align="left">14</td>
<td align="left">1.6</td>
<td align="left">2.56</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">4</td>
<td align="left">15</td>
<td align="left">2.6</td>
<td align="left">6.76</td>
</tr>
<tr class="odd">
<td align="left"></td>
<td align="left">5</td>
<td align="left">4</td>
<td align="left">-8.4</td>
<td align="left">70.56</td>
</tr>
</tbody>
</table>
<ul>
<li>That last column contains all of our squared deviations, so all we have to do is average them. If we do that by typing all the numbers into R by hand…</li>
</ul>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="descriptive-statistics.html#cb71-1" aria-hidden="true" tabindex="-1"></a>( <span class="fl">0.16+21.16+2.56+6.76+70.56</span> ) <span class="sc">/</span> (<span class="dv">5-1</span>)</span></code></pre></div>
<pre><code>## [1] 25.3</code></pre>
<ul>
<li><p>We end up with a variance of 25.3. Exciting, isn’t it? For the moment, let’s ignore the burning question that you’re all probably thinking (i.e., what the heck does a variance of 25.3 actually mean?) and instead talk a bit more about how to do the calculations in R.</p></li>
<li><p>As always, we want to avoid having to type in a whole lot of numbers ourselves. And as it happens, we have the vector <code>X</code> lying around, which we created in the previous section. With this in mind, we can calculate the variance of <code>X</code> by using the following command,</p></li>
</ul>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="descriptive-statistics.html#cb73-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> mammalian_sleep<span class="sc">$</span>sleep_total_h[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb73-2"><a href="descriptive-statistics.html#cb73-2" aria-hidden="true" tabindex="-1"></a>(X <span class="sc">-</span> <span class="fu">mean</span>(X) )<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> (<span class="fu">length</span>(X) <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1]  0.04  5.29  0.64  1.69 17.64</code></pre>
<p>and as usual we get the same answer as the one that we got when we did everything by hand. However, I <em>still</em> think that this is too much typing. Fortunately, R has a built in function called <code>var()</code> which does calculate variances. So we could also do this…</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="descriptive-statistics.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(X)</span></code></pre></div>
<pre><code>## [1] 25.3</code></pre>
<p>and you get the same answer. Great.</p>
</div>
<div id="sd" class="section level3 hasAnchor" number="6.3.6">
<h3><span class="header-section-number">6.3.6</span> Standard deviation<a href="descriptive-statistics.html#sd" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><p>One problem with the variance is that it is expressed in odd units. In the case above it’s <span class="math inline">\(h^2\)</span> (<em>hours squared</em>). I know what <span class="math inline">\(m^2\)</span> is, but what are <span class="math inline">\(h^2\)</span>? No idea.</p></li>
<li><p>Suppose that you’d like to have a measure that is expressed in the same units as the data itself (i.e., points, not points-squared). What should you do?</p></li>
<li><p>The solution to the problem is obvious: take the square root of the variance, known as the <strong><em>standard deviation</em></strong>, also called the “root mean squared deviation”, or RMSD. This solves out problem fairly neatly.</p></li>
<li><p>While nobody has a clue what <em>“a variance of 19.95 hours-squared”</em> really means, it’s much easier to understand <em>“a standard deviation of 4.5 hours”</em>, since it’s expressed in the original units.</p></li>
<li><p>It is traditional to refer to the standard deviation of a sample of data as <span class="math inline">\(s_x\)</span>, though “sd” and “std dev.” are also used at times. Because the standard deviation is equal to the square root of the variance, you probably won’t be surprised to see that the formula is:
<span class="math display">\[
s_x = \sqrt{ \frac{1}{N-1} \sum_{i=1}^N \left( X_i - \bar{X} \right)^2 }
\]</span>
<!--
and the R function that we use to calculate it is `sd()`.
However, as you might have guessed from our discussion of the variance, what R actually calculates is slightly different to the formula given above. Just like the we saw with the variance, what R calculates is a version that divides by $N-1$ rather than $N$.
For reasons that will make sense when we return to this topic in Chapter@refch:estimation I'll refer to this new quantity as $\hat\sigma$ (read as: "sigma hat"), and the formula for this is
$$
\hat\sigma = \sqrt{ \frac{1}{N-1} \sum_{i=1}^N \left( X_i - \bar{X} \right)^2 }
$$
With that in mind, calculating standard deviations in R is simple:

```r
sd( mammalian_sleep$sleep_total_h )
```

```
## [1] 4.466777
```
--></p></li>
<li><p>Interpreting standard deviations is slightly more complex. Because the standard deviation is derived from the variance, and the variance is a quantity that has little to no meaning that makes sense to us humans, the standard deviation doesn’t have a simple interpretation.</p></li>
<li><p>As a consequence, most of us just rely on a <strong>simple rule of thumb</strong>: <strong>“in general, you should expect 68% of the data to fall within 1 standard deviation of the mean, 95% of the data to fall within 2 standard deviation of the mean, and 99.7% of the data to fall within 3 standard deviations of the mean”</strong>. This rule tends to work pretty well most of the time, but it’s not exact: it’s actually calculated based on an <em>assumption</em> that the histogram is symmetric and “bell shaped”. (Strictly, the assumption is that the data are <em>normally</em> distributed, which is an important concept that we’ll discuss more later).</p></li>
</ul>
<!-- , applied to the AFL winning margins data. The shaded bars in the histogram show how much of the data fall within one standard deviation of the mean. In this case, 65.3% of the data set lies within this range, which is pretty consistent with the \"approximately 68% rule\" discussed in the main text -->
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="descriptive-statistics.html#cb77-1" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> mammalian_sleep <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a href="descriptive-statistics.html#cb77-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">ggplot</span>(<span class="fu">aes</span>(sleep_total_h)) <span class="sc">+</span></span>
<span id="cb77-3"><a href="descriptive-statistics.html#cb77-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>,</span>
<span id="cb77-4"><a href="descriptive-statistics.html#cb77-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,</span>
<span id="cb77-5"><a href="descriptive-statistics.html#cb77-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">fill =</span> <span class="st">&quot;lightgrey&quot;</span>)</span>
<span id="cb77-6"><a href="descriptive-statistics.html#cb77-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-7"><a href="descriptive-statistics.html#cb77-7" aria-hidden="true" tabindex="-1"></a>  sleep_sd <span class="ot">&lt;-</span> <span class="fu">sd</span>(mammalian_sleep<span class="sc">$</span>sleep_total_h)</span>
<span id="cb77-8"><a href="descriptive-statistics.html#cb77-8" aria-hidden="true" tabindex="-1"></a>  sleep_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(mammalian_sleep<span class="sc">$</span>sleep_total_h)</span>
<span id="cb77-9"><a href="descriptive-statistics.html#cb77-9" aria-hidden="true" tabindex="-1"></a>  bars <span class="ot">&lt;-</span> <span class="fu">c</span>(sleep_mean<span class="sc">-</span>sleep_sd, sleep_mean, sleep_mean<span class="sc">+</span>sleep_sd)</span>
<span id="cb77-10"><a href="descriptive-statistics.html#cb77-10" aria-hidden="true" tabindex="-1"></a>  bar_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;mean-1*sd&quot;</span>, <span class="st">&quot;mean&quot;</span>, <span class="st">&quot;mean+1*sd&quot;</span>)</span>
<span id="cb77-11"><a href="descriptive-statistics.html#cb77-11" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> p <span class="sc">+</span> <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> bars, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb77-12"><a href="descriptive-statistics.html#cb77-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_label</span>(<span class="at">data=</span><span class="cn">NULL</span>, <span class="fu">aes</span>(<span class="at">x=</span>bars[<span class="dv">1</span>], <span class="at">y=</span> <span class="dv">10</span>, <span class="at">label =</span> bar_labels[<span class="dv">1</span>])) <span class="sc">+</span></span>
<span id="cb77-13"><a href="descriptive-statistics.html#cb77-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_label</span>(<span class="at">data=</span><span class="cn">NULL</span>, <span class="fu">aes</span>(<span class="at">x=</span>bars[<span class="dv">2</span>], <span class="at">y=</span> <span class="dv">10</span>, <span class="at">label =</span> bar_labels[<span class="dv">2</span>])) <span class="sc">+</span></span>
<span id="cb77-14"><a href="descriptive-statistics.html#cb77-14" aria-hidden="true" tabindex="-1"></a>      <span class="fu">geom_label</span>(<span class="at">data=</span><span class="cn">NULL</span>, <span class="fu">aes</span>(<span class="at">x=</span>bars[<span class="dv">3</span>], <span class="at">y=</span> <span class="dv">10</span>, <span class="at">label =</span> bar_labels[<span class="dv">3</span>]))</span>
<span id="cb77-15"><a href="descriptive-statistics.html#cb77-15" aria-hidden="true" tabindex="-1"></a>  p</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:aflsd"></span>
<img src="main_files/figure-html/aflsd-1.png" alt="An illustration of the standard deviation." width="672" />
<p class="caption">
Figure 6.10: An illustration of the standard deviation.
</p>
</div>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="descriptive-statistics.html#cb78-1" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(mammalian_sleep, <span class="fu">mean</span>(sleep_total_h<span class="sc">&gt;</span>(sleep_mean<span class="sc">-</span>sleep_sd) <span class="sc">&amp;</span> sleep_total_h<span class="sc">&lt;</span>(sleep_mean<span class="sc">+</span>sleep_sd) ))</span></code></pre></div>
<pre><code>## [1] 0.6385542</code></pre>
<div id="bessels-correction-whats-up-with-all-those-n-1s-in-the-denominator" class="section level4 hasAnchor" number="6.3.6.1">
<h4><span class="header-section-number">6.3.6.1</span> Bessel’s correction: What’s up with all those <span class="math inline">\(N-1\)</span>s in the denominator?<a href="descriptive-statistics.html#bessels-correction-whats-up-with-all-those-n-1s-in-the-denominator" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p>Now, what’s going on with that <span class="math inline">\(N-1\)</span>, and why do I still call the sample variance a <em>‘sort-of-the-average’</em> of the squared deviations? Let’s address these questions in turn.</p></li>
<li><p>The important thing to note about variance and standard deviation is they serve <em>two</em> purposes: They are used to (i) describe a <strong>sample</strong>, but also to (ii) tentatively characterize the larger population from which the sample is.</p></li>
<li><p>You are <em>usually</em> not really interested in the variance of a particular set of numbers, but rather in what they represent. So function number (ii) is the far more dominant use.</p></li>
<li><p>In our case, when I want to quantify the variability of the sleep durations dataset, it is not these 83 specific mammals I am interested in – I want to get a sense of the variability among mammals in general. That is, I want to know – how much do mammals vary <em>in general</em>. These just happen to be a <strong><em>sample</em></strong> (83 mammals) from the <strong><em>population</em></strong> (all mammals).</p></li>
<li><p>What I actually want to compute are not the (squared) deviations from the <strong>sample mean</strong> (<span class="math inline">\(\bar{X}\)</span>; the average sleep duration of <strong>these</strong> mammals), but from the actual <strong>population mean</strong> (<span class="math inline">\(\mu\)</span>; the average sleep duration of <strong>all</strong> mammals). That is, I don’t want <span class="math inline">\(( X_i - \bar{X})^2\)</span>, I want <span class="math inline">\(( X_i - \mu)^2\)</span>.</p></li>
<li><p>But I don’t know <span class="math inline">\(\mu\)</span>, and the <em>best guess</em> I have about it is <span class="math inline">\(\bar{X}\)</span>. And this has consequences: <span class="math inline">\(( X_i - \bar{X})^2\)</span> underestimates the distance between <span class="math inline">\(X_i\)</span> and <span class="math inline">\(\mu\)</span> because we use the same data points (<span class="math inline">\(X_i\)</span>) to compute the mean (<span class="math inline">\(\bar{X}\)</span>) and then determine the distance to them.</p></li>
</ul>
<!--
- Consider what happens to $( X_i - \bar{X})^2$ in the rather extreme cases of
  * $N=1$? -- The distance is zero.
  * $N=2$? -- If both points happen to be equidistant to the mean.
-->
<ul>
<li><p>The problem becomes smaller as <span class="math inline">\(N\)</span> increases, because it becomes less and less likely that all <span class="math inline">\(N\)</span> points are squarely on one side of the mean.</p></li>
<li><p>Dividing by <span class="math inline">\(N-1\)</span> <em>‘corrects’</em> this underestimation problem:</p>
<ul>
<li>Dividing by a smaller number makes the estimate of the variance bigger.</li>
<li>As <span class="math inline">\(N\)</span> increases the difference between dividing by <span class="math inline">\(N\)</span> and <span class="math inline">\(N-1\)</span> becomes less and less important, and ultimately negligible.</li>
</ul></li>
</ul>
<div id="summary-1" class="section level5 hasAnchor" number="6.3.6.1.1">
<h5><span class="header-section-number">6.3.6.1.1</span> Summary<a href="descriptive-statistics.html#summary-1" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<ul>
<li>To recap, these are the two estimators of the variance, but the second one requires knowledge of the true population mean <span class="math inline">\(\mu\)</span>, which we don’t know.</li>
<li>Therefore, we use the first one (<span class="math inline">\(s_X^2\)</span>), and divide by <span class="math inline">\(N-1\)</span> to avoid underestimating the ‘true variance’.</li>
</ul>
<p><span class="math display">\[
\mbox{s}_X^2 = \frac{1}{N-1} \sum_{i=1}^N \left( X_i - \bar{X} \right)^2
\]</span></p>
<p><span class="math display">\[
\mbox{Var}_X = \frac{1}{N} \sum_{i=1}^N \left( X_i - \mu \right)^2
\]</span></p>
<!--
---
- Let's simulate this with the sleep data:


```r
n = 5 # sample size
k = 10 # number of samples

draw_one_sample <- function(idx) {
  current_sample <- sample(mammalian_sleep$sleep_total_h, size = n)
  data.frame(sample_index=idx, sleep_total_h = current_sample, sample_mean = mean(current_sample))
}

set.seed(1234)
samples_of_5 <- plyr::ldply(1:k, draw_one_sample)

p_all_83_mammals <- ggplot(mammalian_sleep, aes(sleep_total_h)) + geom_histogram(binwidth = 2, color="black") + geom_vline(aes(xintercept = mean(sleep_total_h) ), color = "red")

p_samples <- ggplot(samples_of_5, aes(sleep_total_h)) + geom_histogram(binwidth = 2, color="black") + facet_wrap(~paste("sample", sample_index), nrow=1) + geom_vline(aes(xintercept = sample_mean ), color = "blue") + geom_vline(xintercept = mean(mammalian_sleep$sleep_total_h), color = "red") + scale_x_continuous(breaks=c(0,10,20))

library(ggpubr)
ggarrange(p_all_83_mammals, p_samples, ncol=1, nrow=2, labels = c("'Population'", "Samples"))
```

<img src="main_files/figure-html/unnamed-chunk-39-1.png" width="672" />
-->
<!--

<!-- - The real question is *why* R is dividing by $N-1$ and not by $N$. After all, the variance is supposed to be the *mean* squared deviation, right? So shouldn't we be dividing by $N$, the actual number of observations in the sample? Well, yes, we should. However, there's a subtle distinction between "describing a sample" and "making guesses about the population from which the sample came". Up to this point, it's been a distinction without a difference. Regardless of whether you're describing a sample or drawing inferences about the population, the mean is calculated exactly the same way. Not so for the variance, or the standard deviation, or for many other measures besides. What I outlined to you initially (i.e., take the actual average, and thus divide by $N$) assumes that you literally intend to calculate the variance of the sample. Most of the time, however, you're not terribly interested in the sample *in and of itself*. Rather, the sample exists to tell you something about the world. If so, you're actually starting to move away from calculating a "sample statistic", and towards the idea of estimating a "population parameter".  -->
<!-- Okay, one last thing. This section so far has read a bit like a mystery novel. I've shown you how to calculate the variance, described the weird "$N-1$" thing that R does and hinted at the reason why it's there, but I haven't mentioned the single most important thing... how do you *interpret* the variance? Descriptive statistics are supposed to describe things, after all, and right now the variance is really just a gibberish number. Unfortunately, the reason why I haven't given you the human-friendly interpretation of the variance is that there really isn't one. This is the most serious problem with the variance. Although it has some elegant mathematical properties that suggest that it really is a fundamental quantity for expressing variation, it's completely useless if you want to communicate with an actual human... variances are completely uninterpretable in terms of the original variable! All the numbers have been squared, and they don't mean anything anymore. This is a huge issue. For instance, according to the table I presented earlier, the margin in game 1 was "376.36 points-squared higher than the average margin". This is *exactly* as stupid as it sounds; and so when we calculate a variance of 324.64, we're in the same situation. I've watched a lot of footy games, and never has anyone referred to "points squared". It's *not* a real unit of measurement, and since the variance is expressed in terms of this gibberish unit, it is totally meaningless to a human. -->
<!-- -->
<p>–&gt;</p>
<!-- <!-- -->
<!-- ### Median absolute deviation{#mad} -->
<!-- The last measure of variability that I want to talk about is the **_median absolute deviation_** (MAD). The basic idea behind MAD is very simple, and is pretty much identical to the idea behind the mean absolute deviation (Section \@ref(aad)). The difference is that you use the median everywhere. If we were to frame this idea as a pair of R commands, they would look like this: -->
<!-- ```{r} -->
<!-- # mean absolute deviation from the mean: -->
<!-- #mean( abs(afl.margins - mean(afl.margins)) ) -->
<!-- # *median* absolute deviation from the *median*: -->
<!-- #median( abs(afl.margins - median(afl.margins)) ) -->
<!-- ``` -->
<!-- This has a straightforward interpretation: every observation in the data set lies some distance away from the typical value (the median). So the MAD is an attempt to describe a *typical deviation from a typical value* in the data set. It wouldn't be unreasonable to interpret the MAD value of 19.5 for our AFL data by saying something like this: -->
<!-- >The median winning margin in 2010 was 30.5, indicating that a typical game involved a winning margin of about 30 points. However, there was a fair amount of variation from game to game: the MAD value was 19.5, indicating that a typical winning margin would differ from this median value by about 19-20 points. -->
<!-- As you'd expect, R has a built in function for calculating MAD, and you will be shocked no doubt to hear that it's called `mad()`. However, it's a little bit more complicated than the functions that we've been using previously. If you want to use it to calculate MAD in the exact same way that I have described it above, the command that you need to use specifies two arguments: the data set itself `x`, and a `constant` that I'll explain in a moment. For our purposes, the constant is 1, so our command becomes -->
<!-- ```{r} -->
<!-- #mad( x = afl.margins, constant = 1 ) -->
<!-- ``` -->
<!-- Apart from the weirdness of having to type that `constant = 1` part, this is pretty straightforward. -->
<!-- Okay, so what exactly is this `constant = 1` argument? I won't go into all the details here, but here's the gist. Although the "raw" MAD value that I've described above is completely interpretable on its own terms, that's not actually how it's used in a lot of real world contexts. Instead, what happens a lot is that the researcher *actually* wants to calculate the standard deviation. However, in the same way that the mean is very sensitive to extreme values, the standard deviation is vulnerable to the exact same issue. So, in much the same way that people sometimes use the median as a "robust" way of calculating "something that is like the mean", it's not uncommon to use MAD as a method for calculating "something that is like the standard deviation". Unfortunately, the *raw* MAD value doesn't do this. Our raw MAD value is 19.5, and our standard deviation was 26.07. However, what some clever person has shown is that, under certain assumptions^[The assumption again being that the data are normally-distributed!], you can multiply the raw MAD value by 1.4826 and obtain a number that is directly comparable to the standard deviation. As a consequence, the default value of `constant` is 1.4826, and so when you use the `mad()` command without manually setting a value, here's what you get: -->
<!-- ```{r} -->
<!-- #mad( afl.margins ) -->
<!-- ``` -->
<!-- I should point out, though, that if you want to use this "corrected" MAD value as a robust version of the standard deviation, you really are relying on the assumption that the data are (or at least, are "supposed to be" in some sense) symmetric and basically shaped like a bell curve. That's really *not* true for our `afl.margins` data, so in this case I wouldn't try to use the MAD value this way. -->
<!-- -->
<p>–&gt;</p>
</div>
</div>
</div>
<div id="which-measure-to-use" class="section level3 hasAnchor" number="6.3.7">
<h3><span class="header-section-number">6.3.7</span> Which measure to use?<a href="descriptive-statistics.html#which-measure-to-use" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ve discussed quite a few measures of spread (range, IQR, variance and standard deviation). Below is a quick summary.
In short, the IQR and the standard deviation are easily the two most common measures used to report the variability of the data.</p>
<ul>
<li><em>Range</em>. Gives you the full spread of the data. It’s very vulnerable to outliers, and as a consequence it isn’t often used unless you have good reasons to care about the extremes in the data.</li>
<li><em>Interquartile range</em>. Tells you where the “middle half” of the data sits. It’s pretty robust, and complements the median nicely. This is used a lot.
<!--
- *Mean absolute deviation*. Tells you how far "on average" the observations are from the mean. It's very interpretable, but has a few minor issues (not discussed here) that make it less attractive to statisticians than the standard deviation. Used sometimes, but not often.
--></li>
<li><em>Variance</em>. Tells you the average squared deviation from the mean. It’s mathematically elegant, and is probably the “right” way to describe variation around the mean, but it’s completely uninterpretable because it doesn’t use the same units as the data. Almost never used except as a mathematical tool; but it’s buried “under the hood” of a very large number of statistical tools.</li>
<li><em>Standard deviation</em>. This is the square root of the variance. It’s fairly elegant mathematically, and it’s expressed in the same units as the data so it can be interpreted pretty well. In situations where the mean is the measure of central tendency, this is the default. This is by far the most popular measure of variation.</li>
</ul>
<!-- <!-- -->
<!-- ## Skew and kurtosis{#skewandkurtosis} -->
<!-- There are two more descriptive statistics that you will sometimes see reported in the psychological literature, known as skew and kurtosis. In practice, neither one is used anywhere near as frequently as the measures of central tendency and variability that we've been talking about. Skew is pretty important, so you do see it mentioned a fair bit; but I've actually never seen kurtosis reported in a scientific article to date.  -->
<!-- ```{r eval=F, skewness, fig.cap="An illustration of skewness. On the left we have a negatively skewed data set (skewness $= -.93$), in the middle we have a data set with no skew (technically, skewness $= -.006$), and on the right we have a positively skewed data set (skewness $= .93$).", echo=FALSE} -->
<!-- library(psych) -->
<!--    x1 <- rbeta(n = 100000, shape1= 10, shape2 = 2) -->
<!--    x2 <- rbeta(n = 100000, shape1= 10, shape2 = 10) -->
<!--    x3 <- rbeta(n = 100000, shape1= 2, shape2 = 10) -->
<!--    X <- list(x1,x2,x3) -->
<!--    plot.new() -->
<!--    old <- par(no.readonly = TRUE) -->
<!--    par(mfrow=c(1,3)) -->
<!--    ttl = c("Negative Skew", "No Skew", "Positive Skew") -->
<!--    for (i in 1:3) { -->
<!--      hist(x = X[[i]], -->
<!--           breaks = seq(0,1,.05), -->
<!--           xlab = "", -->
<!--           ylab = "", -->
<!--           main = ttl[i], -->
<!--           axes = FALSE, -->
<!--           col = "cornflowerblue", -->
<!--           border = "white", -->
<!--            font.main = 1 -->
<!--           ) -->
<!--      print(skew(X[[i]])) -->
<!--    } -->
<!--    par( old ) -->
<!-- ``` -->
<!-- Since it's the more interesting of the two, let's start by talking about the **_skewness_**. Skewness is basically a measure of asymmetry, and the easiest way to explain it is by drawing some pictures. As Figure \@ref(fig:skewness) illustrates, if the data tend to have a lot of extreme small values (i.e., the lower tail is "longer" than the upper tail) and not so many extremely large values (left panel), then we say that the data are *negatively skewed*. On the other hand, if there are more extremely large values than extremely small ones (right panel) we say that the data are *positively skewed*. That's the qualitative idea behind skewness. The actual formula for the skewness of a data set is as follows -->
<!-- $$ -->
<!-- \mbox{skewness}(X) = \frac{1}{N \hat{\sigma}^3} \sum_{i=1}^N (X_i - \bar{X})^3 -->
<!-- $$ -->
<!-- where $N$ is the number of observations, $\bar{X}$ is the sample mean, and $\hat{\sigma}$ is the standard deviation (the "divide by $N-1$" version, that is). Perhaps more helpfully, it might be useful to point out that the `psych` package contains a `skew()` function that you can use to calculate skewness. So if we wanted to use this function to calculate the skewness of the `afl.margins` data, we'd first need to load the package -->
<!-- ```{r eval=F} -->
<!-- library( psych ) -->
<!-- ``` -->
<!-- which now makes it possible to use the following command: -->
<!-- ```{r eval=F} -->
<!-- skew( x = afl.margins ) -->
<!-- ``` -->
<!-- Not surprisingly, it turns out that the AFL winning margins data is fairly skewed. -->
<!-- The final measure that is sometimes referred to, though very rarely in practice, is the **_kurtosis_** of a data set. Put simply, kurtosis is a measure of the "pointiness" of a data set, as illustrated in Figure \@ref(fig:kurtosis).  -->
<!-- ```{r eval=F, kurtosis, fig.cap="An illustration of kurtosis. On the left, we have a \"platykurtic\" data set (kurtosis = $-.95$), meaning that the data set is \"too flat\". In the middle we have a \"mesokurtic\" data set (kurtosis is almost exactly 0), which means that the pointiness of the data is just about right. Finally, on the right, we have a \"leptokurtic\" data set (kurtosis $= 2.12$) indicating that the data set is \"too pointy\". Note that kurtosis is measured with respect to a normal curve (black line)", echo=FALSE} -->
<!--    #x1 <- c(rexp(n = 5000, rate =2), -rexp(n = 5000, rate =2) ) -->
<!--    x3 <- c(rnorm(n = 50000, mean =0, sd = 1), (runif(n = 50000)-.5)+rnorm(50000,0,.1) )*1.6 -->
<!--    x2 <- rnorm(n = 100000, mean = 0, sd = 1)*1.2 -->
<!--    x1 <- (runif(n = 100000) + rnorm(100000, mean =0, sd = .1) -.5)*4 -->
<!--    X <- list(x1,x2,x3) -->
<!--    plot.new() -->
<!--    old <- par(no.readonly = TRUE) -->
<!--    par(mfrow=c(1,3)) -->
<!--    ttl = c( 'Platykurtic\n("too flat")','Mesokurtic', 'Leptokurtic\n("too pointy")') -->
<!--    for (i in 1:3) { -->
<!--        hist(x = X[[i]], -->
<!--            breaks = seq(-20.5,20.5,.5), -->
<!--            ylim =c(0,.45), -->
<!--            xlim = c(-5,5), -->
<!--            xlab = "", -->
<!--            ylab = "", -->
<!--            main = ttl[i], -->
<!--            axes = FALSE, -->
<!--            freq = FALSE, -->
<!--        col = "cornflowerblue", -->
<!--            font.main=1, -->
<!--            border = "white" -->
<!--        ) -->
<!--        lines(x <- seq(-4,4,.01), y = dnorm(x, mean(X[[i]]), sd(X[[i]])),  -->
<!--            lwd = 2, lty = 1, col = "black") -->
<!--        print(kurtosi(X[[i]])) -->
<!--    } -->
<!--    par( old ) -->
<!-- ``` -->
<!-- By convention, we say that the "normal curve" (black lines) has zero kurtosis, so the pointiness of a data set is assessed relative to this curve. In this Figure, the data on the left are not pointy enough, so the kurtosis is negative and we call the data *platykurtic*. The data on the right are too pointy, so the kurtosis is positive and we say that the data is *leptokurtic*. But the data in the middle are just pointy enough, so we say that it is *mesokurtic* and has kurtosis zero. This is summarised in the table below: -->
<!-- ```{r eval=F, echo=FALSE} -->
<!-- knitr::kable(rbind( -->
<!--                   c("too flat" , "platykurtic", "negative"), -->
<!--                   c("just pointy enough", "mesokurtic", "zero"), -->
<!--                   c("too pointy", "leptokurtic", "positive")), -->
<!-- col.names = c("informal term", "technical name", "kurtosis value"), -->
<!--   booktabs = TRUE) -->
<!-- ``` -->
<!-- The equation for kurtosis is pretty similar in spirit to the formulas we've seen already for the variance and the skewness; except that where the variance involved squared deviations and the skewness involved cubed deviations, the kurtosis involves raising the deviations to the fourth power:^[The "$-3$" part is something that statisticians tack on to ensure that the normal curve has kurtosis zero. It looks a bit stupid, just sticking a "-3" at the end of the formula, but there are good mathematical reasons for doing this.] -->
<!-- $$ -->
<!-- \mbox{kurtosis}(X) = \frac{1}{N \hat\sigma^4} \sum_{i=1}^N \left( X_i - \bar{X} \right)^4  - 3 -->
<!-- $$ -->
<!-- I know, it's not terribly interesting to me either. More to the point, the `psych` package has a function called `kurtosi()` that you can use to calculate the kurtosis of your data. For instance, if we were to do this for the AFL margins,  -->
<!-- ```{r eval=FALSE} -->
<!-- kurtosi( x = afl.margins ) -->
<!-- ``` -->
<!-- we discover that the AFL winning margins data are just pointy enough. -->
<!-- -->
<p>–&gt;</p>
</div>
</div>
<div id="summary" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Getting an overall summary of a variable<a href="descriptive-statistics.html#summary" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>It’s kind of annoying to have to separately calculate means, medians, standard deviations, etc. Wouldn’t it be nice if R had some helpful functions that would do all these tedious calculations at once? Something like <code>summary()</code>, perhaps?</li>
<li>The basic idea behind the <code>summary()</code> function is that it prints out some useful information about whatever object it receives (e.g., a vector or data frame).</li>
<li>Let’s take a look at some examples:</li>
</ul>
<div id="summarising-a-vector" class="section level3 hasAnchor" number="6.4.1">
<h3><span class="header-section-number">6.4.1</span> Summarising a vector<a href="descriptive-statistics.html#summarising-a-vector" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="numerical-vectors" class="section level4 hasAnchor" number="6.4.1.1">
<h4><span class="header-section-number">6.4.1.1</span> Numerical vectors<a href="descriptive-statistics.html#numerical-vectors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>For numeric variables, we get a whole bunch of useful descriptive statistics. It gives us the minimum and maximum values (and thus the range), the first and third quartiles (25th and 75th percentiles; and thus the IQR), the mean and the median.</li>
<li>In sum, it gives us a pretty good collection of descriptive statistics related to the central tendency and the spread of the data.</li>
</ul>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="descriptive-statistics.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( mammalian_sleep<span class="sc">$</span>sleep_total_h )</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    2.00    8.00   10.00   10.41   14.00   20.00</code></pre>
</div>
<div id="logical-vectors" class="section level4 hasAnchor" number="6.4.1.2">
<h4><span class="header-section-number">6.4.1.2</span> Logical vectors<a href="descriptive-statistics.html#logical-vectors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>Returns the number of <code>TRUE</code> and <code>FALSE</code> values.</li>
</ul>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="descriptive-statistics.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( mammalian_sleep<span class="sc">$</span>sleep_total_h <span class="sc">&gt;</span> <span class="dv">10</span> )</span></code></pre></div>
<pre><code>##    Mode   FALSE    TRUE 
## logical      45      38</code></pre>
</div>
<div id="factors-vectors" class="section level4 hasAnchor" number="6.4.1.3">
<h4><span class="header-section-number">6.4.1.3</span> Factors vectors<a href="descriptive-statistics.html#factors-vectors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>Returns the number of observations for each factor level.</li>
</ul>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="descriptive-statistics.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( <span class="fu">as.factor</span>(mammalian_sleep<span class="sc">$</span>name[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]) )</span></code></pre></div>
<pre><code>##                    Cheetah                        Cow 
##                          1                          1 
##                        Dog Greater short-tailed shrew 
##                          1                          1 
##            Mountain beaver          Northern fur seal 
##                          1                          1 
##                 Owl monkey                   Roe deer 
##                          1                          1 
##           Three-toed sloth               Vesper mouse 
##                          1                          1</code></pre>
</div>
<div id="character-vectors" class="section level4 hasAnchor" number="6.4.1.4">
<h4><span class="header-section-number">6.4.1.4</span> Character vectors<a href="descriptive-statistics.html#character-vectors" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>Returns almost no useful information except for length.</li>
</ul>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="descriptive-statistics.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( mammalian_sleep<span class="sc">$</span>name )</span></code></pre></div>
<pre><code>##    Length     Class      Mode 
##        83 character character</code></pre>
</div>
</div>
<div id="summarising-a-data-frame" class="section level3 hasAnchor" number="6.4.2">
<h3><span class="header-section-number">6.4.2</span> Summarising a data frame<a href="descriptive-statistics.html#summarising-a-data-frame" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><code>summary()</code> can also be called on a data frame, in which case it returns summaries of all variables.</li>
</ul>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="descriptive-statistics.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>( mammalian_sleep )</span></code></pre></div>
<pre><code>##      name           sleep_total_h     bodywt_kg       
##  Length:83          Min.   : 2.00   Min.   :   0.005  
##  Class :character   1st Qu.: 8.00   1st Qu.:   0.174  
##  Mode  :character   Median :10.00   Median :   1.670  
##                     Mean   :10.41   Mean   : 166.136  
##                     3rd Qu.:14.00   3rd Qu.:  41.750  
##                     Max.   :20.00   Max.   :6654.000</code></pre>
</div>
</div>
<div id="correlations" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> Correlations<a href="descriptive-statistics.html#correlations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The descriptive statistics we discussed so far were all about a single variable. Sometimes, we want to describe the relation between two variables. For this we need to calculate <strong>correlations</strong>. Correlations range between -1 and 1. 0 means no no correlation, 1 means strong positive correlation and -1 means strong negative correlation. Correlation is indicated by the letter <code>r</code>.</p>
<div class="figure"><span style="display:block;" id="fig:correlations"></span>
<img src="img/corr-1.png" alt="Different correlations."  />
<p class="caption">
Figure 6.11: Different correlations.
</p>
</div>
<p>In R, we can calculate the correlations of two variables using the <code>cor()</code> function. Consider the following example.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="descriptive-statistics.html#cb90-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span></span>
<span id="cb90-2"><a href="descriptive-statistics.html#cb90-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> (x<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb90-3"><a href="descriptive-statistics.html#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="descriptive-statistics.html#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span><span class="cn">NULL</span>, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y=</span>y)) <span class="sc">+</span></span>
<span id="cb90-5"><a href="descriptive-statistics.html#cb90-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-45-1.png" width="672" /></p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="descriptive-statistics.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(x,y)</span></code></pre></div>
<pre><code>## [1] 0.9713482</code></pre>

</div>
</div>








<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>The choice to use <span class="math inline">\(\Sigma\)</span> to denote summation isn’t arbitrary: it’s the Greek upper case letter sigma, which is the analogue of the letter S in that alphabet. Similarly, there’s an equivalent symbol used to denote the multiplication of lots of numbers: because multiplications are also called “products”, we use the <span class="math inline">\(\Pi\)</span> symbol for this; the Greek upper case pi, which is the analogue of the letter P.<a href="descriptive-statistics.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Or at least, the basic statistical theory – these days there is a whole subfield of statistics called <em>robust statistics</em> that tries to grapple with the messiness of real data and develop theory that can cope with it.<a href="descriptive-statistics.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>I will very briefly mention the one that I think is coolest, for a very particular definition of “cool”, that is. Variances are <em>additive</em>. Here’s what that means: suppose I have two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, whose variances are <span class="math inline">\(\mbox{Var}(X)\)</span> and <span class="math inline">\(\mbox{Var}(Y)\)</span> respectively. Now imagine I want to define a new variable <span class="math inline">\(Z\)</span> that is the sum of the two, <span class="math inline">\(Z = X+Y\)</span>. As it turns out, the variance of <span class="math inline">\(Z\)</span> is equal to <span class="math inline">\(\mbox{Var}(X) + \mbox{Var}(Y)\)</span>. This is a <em>very</em> useful property, but it’s not true of the other measures that I talk about in this section.<a href="descriptive-statistics.html#fnref3" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="plotting-1.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/05-desc_stats.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["main.pdf", "main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
