<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 Logistic Regression | Ling 411 - Fall 2023</title>
  <meta name="description" content="This is an R tutorial for the Ling 411 Class at Boğaziçi University in Fall 2023." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 Logistic Regression | Ling 411 - Fall 2023" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is an R tutorial for the Ling 411 Class at Boğaziçi University in Fall 2023." />
  <meta name="github-repo" content="rstudio/ling_411" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 Logistic Regression | Ling 411 - Fall 2023" />
  
  <meta name="twitter:description" content="This is an R tutorial for the Ling 411 Class at Boğaziçi University in Fall 2023." />
  

<meta name="author" content="Ümit Atlamaz" />


<meta name="date" content="2023-12-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="effect-size-significance.html"/>
<link rel="next" href="modeling-poisson-distribution.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.2/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.30/datatables.js"></script>
<link href="libs/dt-core-1.13.4/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.13.4/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.13.4/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Ling 411 - Fall 2023</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#disclaimer"><i class="fa fa-check"></i><b>1.1</b> Disclaimer</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#some-great-resources"><i class="fa fa-check"></i><b>1.2</b> Some great resources</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#blocks"><i class="fa fa-check"></i><b>1.3</b> Blocks</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics.html"><a href="basics.html"><i class="fa fa-check"></i><b>2</b> Basics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basics.html"><a href="basics.html#basic-math-operations"><i class="fa fa-check"></i><b>2.1</b> Basic Math Operations</a></li>
<li class="chapter" data-level="2.2" data-path="basics.html"><a href="basics.html#operators"><i class="fa fa-check"></i><b>2.2</b> Operators</a></li>
<li class="chapter" data-level="2.3" data-path="basics.html"><a href="basics.html#variables-and-assignment"><i class="fa fa-check"></i><b>2.3</b> Variables and Assignment</a></li>
<li class="chapter" data-level="2.4" data-path="basics.html"><a href="basics.html#data-types"><i class="fa fa-check"></i><b>2.4</b> Data Types</a></li>
<li class="chapter" data-level="2.5" data-path="basics.html"><a href="basics.html#determining-the-data-type"><i class="fa fa-check"></i><b>2.5</b> Determining the data type</a></li>
<li class="chapter" data-level="2.6" data-path="basics.html"><a href="basics.html#changing-the-types"><i class="fa fa-check"></i><b>2.6</b> Changing the types</a></li>
<li class="chapter" data-level="2.7" data-path="basics.html"><a href="basics.html#installing-packages"><i class="fa fa-check"></i><b>2.7</b> Installing packages</a></li>
<li class="chapter" data-level="2.8" data-path="basics.html"><a href="basics.html#plotting"><i class="fa fa-check"></i><b>2.8</b> Plotting</a></li>
<li class="chapter" data-level="2.9" data-path="basics.html"><a href="basics.html#operators-and-functions-in-this-section"><i class="fa fa-check"></i><b>2.9</b> Operators and functions in this section</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="basics.html"><a href="basics.html#operators-1"><i class="fa fa-check"></i><b>2.9.1</b> Operators</a></li>
<li class="chapter" data-level="2.9.2" data-path="basics.html"><a href="basics.html#functions"><i class="fa fa-check"></i><b>2.9.2</b> Functions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-structures.html"><a href="data-structures.html"><i class="fa fa-check"></i><b>3</b> Data Structures</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-structures.html"><a href="data-structures.html#data-types-in-r"><i class="fa fa-check"></i><b>3.1</b> Data Types in R</a></li>
<li class="chapter" data-level="3.2" data-path="data-structures.html"><a href="data-structures.html#data-structures-in-r"><i class="fa fa-check"></i><b>3.2</b> Data Structures in R</a></li>
<li class="chapter" data-level="3.3" data-path="data-structures.html"><a href="data-structures.html#vectors"><i class="fa fa-check"></i><b>3.3</b> Vectors</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-structures.html"><a href="data-structures.html#what-are-vectors-good-for"><i class="fa fa-check"></i><b>3.3.1</b> What are vectors good for?</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-structures.html"><a href="data-structures.html#data-frames"><i class="fa fa-check"></i><b>3.4</b> Data Frames</a></li>
<li class="chapter" data-level="3.5" data-path="data-structures.html"><a href="data-structures.html#working-with-data-frames"><i class="fa fa-check"></i><b>3.5</b> Working with data frames</a></li>
<li class="chapter" data-level="3.6" data-path="data-structures.html"><a href="data-structures.html#functions-in-this-section"><i class="fa fa-check"></i><b>3.6</b> Functions in this section</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="working-with-data.html"><a href="working-with-data.html"><i class="fa fa-check"></i><b>4</b> Working with Data</a>
<ul>
<li class="chapter" data-level="4.1" data-path="working-with-data.html"><a href="working-with-data.html#basic-dataframes"><i class="fa fa-check"></i><b>4.1</b> Basic dataframes</a></li>
<li class="chapter" data-level="4.2" data-path="working-with-data.html"><a href="working-with-data.html#tibbles"><i class="fa fa-check"></i><b>4.2</b> Tibbles</a></li>
<li class="chapter" data-level="4.3" data-path="working-with-data.html"><a href="working-with-data.html#beyond-toy-data"><i class="fa fa-check"></i><b>4.3</b> Beyond Toy Data</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="working-with-data.html"><a href="working-with-data.html#reading-data-from-a-csv-file"><i class="fa fa-check"></i><b>4.3.1</b> Reading data from a csv file</a></li>
<li class="chapter" data-level="4.3.2" data-path="working-with-data.html"><a href="working-with-data.html#reading-data-from-r-data-packages"><i class="fa fa-check"></i><b>4.3.2</b> Reading data from R data packages</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="working-with-data.html"><a href="working-with-data.html#summarizing-data"><i class="fa fa-check"></i><b>4.4</b> Summarizing Data</a></li>
<li class="chapter" data-level="4.5" data-path="working-with-data.html"><a href="working-with-data.html#working-with-dplyr"><i class="fa fa-check"></i><b>4.5</b> Working with dplyr</a></li>
<li class="chapter" data-level="4.6" data-path="working-with-data.html"><a href="working-with-data.html#pipes"><i class="fa fa-check"></i><b>4.6</b> Pipes</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="working-with-data.html"><a href="working-with-data.html#the-problem"><i class="fa fa-check"></i><b>4.6.1</b> The problem</a></li>
<li class="chapter" data-level="4.6.2" data-path="working-with-data.html"><a href="working-with-data.html#pipes-1"><i class="fa fa-check"></i><b>4.6.2</b> Pipes</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="plotting-1.html"><a href="plotting-1.html"><i class="fa fa-check"></i><b>5</b> Plotting</a>
<ul>
<li class="chapter" data-level="5.1" data-path="plotting-1.html"><a href="plotting-1.html#the-basics-of-ggplot2"><i class="fa fa-check"></i><b>5.1</b> The basics of ggplot2</a></li>
<li class="chapter" data-level="5.2" data-path="plotting-1.html"><a href="plotting-1.html#the-basics-of-ggplot2-1"><i class="fa fa-check"></i><b>5.2</b> The basics of ggplot2</a></li>
<li class="chapter" data-level="5.3" data-path="plotting-1.html"><a href="plotting-1.html#using-lines-in-plots"><i class="fa fa-check"></i><b>5.3</b> Using lines in plots</a></li>
<li class="chapter" data-level="5.4" data-path="plotting-1.html"><a href="plotting-1.html#color-and-fill"><i class="fa fa-check"></i><b>5.4</b> Color and fill</a></li>
<li class="chapter" data-level="5.5" data-path="plotting-1.html"><a href="plotting-1.html#grouping-and-facets"><i class="fa fa-check"></i><b>5.5</b> Grouping and facets</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>6</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#distributions"><i class="fa fa-check"></i><b>6.1</b> Distributions</a></li>
<li class="chapter" data-level="6.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#centraltendency"><i class="fa fa-check"></i><b>6.2</b> Measures of central tendency</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean"><i class="fa fa-check"></i><b>6.2.1</b> The mean</a></li>
<li class="chapter" data-level="6.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#calculating-the-mean-in-r"><i class="fa fa-check"></i><b>6.2.2</b> Calculating the mean in R</a></li>
<li class="chapter" data-level="6.2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#median"><i class="fa fa-check"></i><b>6.2.3</b> The median</a></li>
<li class="chapter" data-level="6.2.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mean-or-median-whats-the-difference"><i class="fa fa-check"></i><b>6.2.4</b> Mean or median? What’s the difference?</a></li>
<li class="chapter" data-level="6.2.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#trimmedmean"><i class="fa fa-check"></i><b>6.2.5</b> Trimmed mean</a></li>
<li class="chapter" data-level="6.2.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#mode"><i class="fa fa-check"></i><b>6.2.6</b> Mode</a></li>
<li class="chapter" data-level="6.2.7" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary"><i class="fa fa-check"></i><b>6.2.7</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#var"><i class="fa fa-check"></i><b>6.3</b> Measures of variability</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#range"><i class="fa fa-check"></i><b>6.3.1</b> Range</a></li>
<li class="chapter" data-level="6.3.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#quantiles-and-percentile"><i class="fa fa-check"></i><b>6.3.2</b> Quantiles and percentile</a></li>
<li class="chapter" data-level="6.3.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#interquartile-range"><i class="fa fa-check"></i><b>6.3.3</b> Interquartile range</a></li>
<li class="chapter" data-level="6.3.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#aad"><i class="fa fa-check"></i><b>6.3.4</b> Mean absolute deviation</a></li>
<li class="chapter" data-level="6.3.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#variance"><i class="fa fa-check"></i><b>6.3.5</b> Variance</a></li>
<li class="chapter" data-level="6.3.6" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#sd"><i class="fa fa-check"></i><b>6.3.6</b> Standard deviation</a></li>
<li class="chapter" data-level="6.3.7" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#which-measure-to-use"><i class="fa fa-check"></i><b>6.3.7</b> Which measure to use?</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary"><i class="fa fa-check"></i><b>6.4</b> Getting an overall summary of a variable</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summarising-a-vector"><i class="fa fa-check"></i><b>6.4.1</b> Summarising a vector</a></li>
<li class="chapter" data-level="6.4.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summarising-a-data-frame"><i class="fa fa-check"></i><b>6.4.2</b> Summarising a data frame</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#correlations"><i class="fa fa-check"></i><b>6.5</b> Correlations</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="linear-regression-with-one-predictor.html"><a href="linear-regression-with-one-predictor.html"><i class="fa fa-check"></i><b>7</b> Linear Regression with one Predictor</a>
<ul>
<li class="chapter" data-level="7.1" data-path="linear-regression-with-one-predictor.html"><a href="linear-regression-with-one-predictor.html#word-frequency-effects"><i class="fa fa-check"></i><b>7.1</b> Word Frequency Effects</a></li>
<li class="chapter" data-level="7.2" data-path="linear-regression-with-one-predictor.html"><a href="linear-regression-with-one-predictor.html#simple-linear-regression"><i class="fa fa-check"></i><b>7.2</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="7.3" data-path="linear-regression-with-one-predictor.html"><a href="linear-regression-with-one-predictor.html#finding-the-regression-line"><i class="fa fa-check"></i><b>7.3</b> Finding the Regression Line</a></li>
<li class="chapter" data-level="7.4" data-path="linear-regression-with-one-predictor.html"><a href="linear-regression-with-one-predictor.html#estimating-the-coefficients"><i class="fa fa-check"></i><b>7.4</b> Estimating the Coefficients</a></li>
<li class="chapter" data-level="7.5" data-path="linear-regression-with-one-predictor.html"><a href="linear-regression-with-one-predictor.html#data-is-messy"><i class="fa fa-check"></i><b>7.5</b> Data is messy</a></li>
<li class="chapter" data-level="7.6" data-path="linear-regression-with-one-predictor.html"><a href="linear-regression-with-one-predictor.html#simplified-frequency-data"><i class="fa fa-check"></i><b>7.6</b> Simplified Frequency Data</a></li>
<li class="chapter" data-level="7.7" data-path="linear-regression-with-one-predictor.html"><a href="linear-regression-with-one-predictor.html#residuals"><i class="fa fa-check"></i><b>7.7</b> Residuals</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="linear-regression-with-one-predictor.html"><a href="linear-regression-with-one-predictor.html#sum-of-squared-errors"><i class="fa fa-check"></i><b>7.7.1</b> Sum of Squared Errors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="linear-regression-with-many-predictors.html"><a href="linear-regression-with-many-predictors.html"><i class="fa fa-check"></i><b>8</b> Linear Regression with Many Predictors</a>
<ul>
<li class="chapter" data-level="8.1" data-path="linear-regression-with-many-predictors.html"><a href="linear-regression-with-many-predictors.html#fitting-two-linear-models"><i class="fa fa-check"></i><b>8.1</b> Fitting two Linear Models</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="linear-non-linear-transformations.html"><a href="linear-non-linear-transformations.html"><i class="fa fa-check"></i><b>9</b> Linear &amp; Non-Linear Transformations</a>
<ul>
<li class="chapter" data-level="9.1" data-path="linear-non-linear-transformations.html"><a href="linear-non-linear-transformations.html#linear-transformations"><i class="fa fa-check"></i><b>9.1</b> Linear Transformations</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="linear-non-linear-transformations.html"><a href="linear-non-linear-transformations.html#centering"><i class="fa fa-check"></i><b>9.1.1</b> Centering</a></li>
<li class="chapter" data-level="9.1.2" data-path="linear-non-linear-transformations.html"><a href="linear-non-linear-transformations.html#standardizing"><i class="fa fa-check"></i><b>9.1.2</b> Standardizing</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="linear-non-linear-transformations.html"><a href="linear-non-linear-transformations.html#scaling-and-standardizing-in-r"><i class="fa fa-check"></i><b>9.2</b> Scaling and Standardizing in R</a></li>
<li class="chapter" data-level="9.3" data-path="linear-non-linear-transformations.html"><a href="linear-non-linear-transformations.html#non-linear-transformations"><i class="fa fa-check"></i><b>9.3</b> Non-linear Transformations</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="linear-non-linear-transformations.html"><a href="linear-non-linear-transformations.html#logarithms-log-transformation"><i class="fa fa-check"></i><b>9.3.1</b> Logarithms &amp; Log Transformation</a></li>
<li class="chapter" data-level="9.3.2" data-path="linear-non-linear-transformations.html"><a href="linear-non-linear-transformations.html#linear-regression-with-log-transformation"><i class="fa fa-check"></i><b>9.3.2</b> Linear Regression with Log Transformation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="categorical-predictors.html"><a href="categorical-predictors.html"><i class="fa fa-check"></i><b>10</b> Categorical Predictors</a>
<ul>
<li class="chapter" data-level="10.1" data-path="categorical-predictors.html"><a href="categorical-predictors.html#categorical-predictor---continuous-outcome"><i class="fa fa-check"></i><b>10.1</b> Categorical Predictor - Continuous Outcome</a></li>
<li class="chapter" data-level="10.2" data-path="categorical-predictors.html"><a href="categorical-predictors.html#taste-vs.-smell-words"><i class="fa fa-check"></i><b>10.2</b> Taste vs. Smell Words</a></li>
<li class="chapter" data-level="10.3" data-path="categorical-predictors.html"><a href="categorical-predictors.html#contrasts-coding"><i class="fa fa-check"></i><b>10.3</b> Contrasts &amp; Coding</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="categorical-predictors.html"><a href="categorical-predictors.html#treatment-coding."><i class="fa fa-check"></i><b>10.3.1</b> Treatment Coding.</a></li>
<li class="chapter" data-level="10.3.2" data-path="categorical-predictors.html"><a href="categorical-predictors.html#sum-coding"><i class="fa fa-check"></i><b>10.3.2</b> Sum Coding</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="categorical-predictors.html"><a href="categorical-predictors.html#categorical-predictors-with-more-than-2-levels"><i class="fa fa-check"></i><b>10.4</b> Categorical Predictors with more than 2 levels</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="effect-size-significance.html"><a href="effect-size-significance.html"><i class="fa fa-check"></i><b>11</b> Effect Size &amp; Significance</a>
<ul>
<li class="chapter" data-level="11.1" data-path="effect-size-significance.html"><a href="effect-size-significance.html#cohens-d"><i class="fa fa-check"></i><b>11.1</b> Cohen’s <em>d</em></a></li>
<li class="chapter" data-level="11.2" data-path="effect-size-significance.html"><a href="effect-size-significance.html#standard-error"><i class="fa fa-check"></i><b>11.2</b> Standard Error</a></li>
<li class="chapter" data-level="11.3" data-path="effect-size-significance.html"><a href="effect-size-significance.html#confidence-interval"><i class="fa fa-check"></i><b>11.3</b> Confidence Interval</a></li>
<li class="chapter" data-level="11.4" data-path="effect-size-significance.html"><a href="effect-size-significance.html#standard-error-of-the-difference-of-two-means"><i class="fa fa-check"></i><b>11.4</b> Standard Error of the difference of two means</a></li>
<li class="chapter" data-level="11.5" data-path="effect-size-significance.html"><a href="effect-size-significance.html#hypothesis-testing"><i class="fa fa-check"></i><b>11.5</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="11.6" data-path="effect-size-significance.html"><a href="effect-size-significance.html#calculating-the-t-score"><i class="fa fa-check"></i><b>11.6</b> Calculating the t-score</a></li>
<li class="chapter" data-level="11.7" data-path="effect-size-significance.html"><a href="effect-size-significance.html#p-value"><i class="fa fa-check"></i><b>11.7</b> p-value</a></li>
<li class="chapter" data-level="11.8" data-path="effect-size-significance.html"><a href="effect-size-significance.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>11.8</b> Type I and Type II Errors</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="effect-size-significance.html"><a href="effect-size-significance.html#type-i-error"><i class="fa fa-check"></i><b>11.8.1</b> Type I Error</a></li>
<li class="chapter" data-level="11.8.2" data-path="effect-size-significance.html"><a href="effect-size-significance.html#typee-ii-error"><i class="fa fa-check"></i><b>11.8.2</b> Typee II Error</a></li>
<li class="chapter" data-level="11.8.3" data-path="effect-size-significance.html"><a href="effect-size-significance.html#statistical-power"><i class="fa fa-check"></i><b>11.8.3</b> Statistical Power</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i><b>12</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="12.1" data-path="logistic-regression.html"><a href="logistic-regression.html#the-intuition"><i class="fa fa-check"></i><b>12.1</b> The Intuition</a></li>
<li class="chapter" data-level="12.2" data-path="logistic-regression.html"><a href="logistic-regression.html#the-math"><i class="fa fa-check"></i><b>12.2</b> The Math</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="logistic-regression.html"><a href="logistic-regression.html#binomial-bernoulli-distributions"><i class="fa fa-check"></i><b>12.2.1</b> Binomial &amp; Bernoulli Distributions</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="logistic-regression.html"><a href="logistic-regression.html#logistic-regression-1"><i class="fa fa-check"></i><b>12.3</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="logistic-regression.html"><a href="logistic-regression.html#log-odds-logits"><i class="fa fa-check"></i><b>12.3.1</b> Log Odds &amp; Logits</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="logistic-regression.html"><a href="logistic-regression.html#logistic-regression-in-r"><i class="fa fa-check"></i><b>12.4</b> Logistic Regression in R</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="logistic-regression.html"><a href="logistic-regression.html#data"><i class="fa fa-check"></i><b>12.4.1</b> Data</a></li>
<li class="chapter" data-level="12.4.2" data-path="logistic-regression.html"><a href="logistic-regression.html#model"><i class="fa fa-check"></i><b>12.4.2</b> Model</a></li>
<li class="chapter" data-level="12.4.3" data-path="logistic-regression.html"><a href="logistic-regression.html#from-logits-to-probabilities"><i class="fa fa-check"></i><b>12.4.3</b> From logits to probabilities</a></li>
<li class="chapter" data-level="12.4.4" data-path="logistic-regression.html"><a href="logistic-regression.html#dative-dataset"><i class="fa fa-check"></i><b>12.4.4</b> Dative Dataset</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="logistic-regression.html"><a href="logistic-regression.html#testing-the-model"><i class="fa fa-check"></i><b>12.5</b> Testing the model</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="modeling-poisson-distribution.html"><a href="modeling-poisson-distribution.html"><i class="fa fa-check"></i><b>13</b> Modeling Poisson Distribution</a>
<ul>
<li class="chapter" data-level="13.1" data-path="modeling-poisson-distribution.html"><a href="modeling-poisson-distribution.html#poisson-distribution"><i class="fa fa-check"></i><b>13.1</b> Poisson Distribution</a></li>
<li class="chapter" data-level="13.2" data-path="modeling-poisson-distribution.html"><a href="modeling-poisson-distribution.html#modeling-with-poisson-distribution"><i class="fa fa-check"></i><b>13.2</b> Modeling with <strong>Poisson distribution</strong></a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="modeling-poisson-distribution.html"><a href="modeling-poisson-distribution.html#data-1"><i class="fa fa-check"></i><b>13.2.1</b> Data</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Ling 411 - Fall 2023</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="logistic-regression" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Chapter 12</span> Logistic Regression<a href="logistic-regression.html#logistic-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>So far, we built linear models where the outcome (i.e. dependent variable) was a continuous value (e.g. reaction time, frequency, etc.). Now, we turn to modeling data where the outcome is a <strong>categorial</strong> value. In particular, we will use <strong>logistic regression</strong> to model <strong>categorical</strong> outcomes where the number of categories is <strong>two</strong>. Some examples are:</p>
<ul>
<li>acceptable – unacceptable expression</li>
<li>NP NP construction – NP PP construction</li>
<li>SOV – SVO word order</li>
<li>accusative present – accusative absent</li>
<li>adult – child</li>
</ul>
<p>For example, we can use <strong>average utterance length</strong> as an indicator of <strong>child speech</strong> vs. <strong>adult speech</strong>. Consider the following artificial toy dataset.</p>
<table>
<thead>
<tr class="header">
<th align="left"><strong>Utterance length </strong></th>
<th align="left"><strong>Utterer</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2</td>
<td align="left">child</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="left">adult</td>
</tr>
<tr class="odd">
<td align="left">12</td>
<td align="left">adult</td>
</tr>
<tr class="even">
<td align="left">3</td>
<td align="left">adult</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="left">child</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="left">adult</td>
</tr>
<tr class="odd">
<td align="left"><strong>5</strong></td>
<td align="left"><strong>???</strong></td>
</tr>
</tbody>
</table>
<p><strong>Given the data set above, can we predict whether it was uttered by a child or an adult?</strong></p>
<p>Notice that the answer is not that straightforward as it is possible that the utterance belongs to a child because it is shortish but on the other hand, we do see that the adults also produce short sentences (e.g. utterance length of 3).</p>
<div id="the-intuition" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> The Intuition<a href="logistic-regression.html#the-intuition" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The core intuition behind logistic regression is very simple. The task is to <strong>model the probability of an outcome given a predictor</strong>. Going back to our toy example above, we would like a model that can produce probabilities like the following.</p>
<ul>
<li><span class="math inline">\(p(child | length = 5)\)</span>
<ul>
<li>read as <em>probability of the utterer being a child given that the utterance length is 5</em>
<br><br />
</li>
</ul></li>
<li><span class="math inline">\(p(adult | length = 5)\)</span>
<ul>
<li>read as <em>probability of the utterer being an adult given that the utterance length is 5</em></li>
</ul></li>
</ul>
<p>For example, we want to build a model that returns something like the following.</p>
<p><img src="main_files/figure-html/unnamed-chunk-278-1.png" width="672" /></p>
<p>Once we estimate the probabilities, we have a model that can:</p>
<ul>
<li><strong>predict</strong> the categorical outcome (e.g. adult vs. child)</li>
<li>help us <strong>interpret</strong> the relationship between a predictor and the outcome</li>
</ul>
<p>Let us now turn to the math behind how the logistic regression works.</p>
</div>
<div id="the-math" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> The Math<a href="logistic-regression.html#the-math" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Remember that our <strong>linear regression</strong> models assumed that our data is <strong>normally distributed</strong>. Normal distribution is a distribution of continuous values. Similarly, for <strong>logistic regression</strong>, we assume that the <strong>outcome variables</strong> come from a certain probability distribution.</p>
<div id="binomial-bernoulli-distributions" class="section level3 hasAnchor" number="12.2.1">
<h3><span class="header-section-number">12.2.1</span> Binomial &amp; Bernoulli Distributions<a href="logistic-regression.html#binomial-bernoulli-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="binomial-distribution" class="section level4 hasAnchor" number="12.2.1.1">
<h4><span class="header-section-number">12.2.1.1</span> Binomial Distribution<a href="logistic-regression.html#binomial-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The <strong>Binomial Distribution</strong> is a discrete probability distribution with a fixed number of <strong>Bernoulli trials</strong> with the parameters:</p>
<ul>
<li><span class="math inline">\(n\)</span> trials</li>
<li><span class="math inline">\(p\)</span> probability</li>
</ul>
<p>where each trial has only two possible outcomes: <strong>success</strong> or <strong>failure</strong>. Success can be associated with any outcome that is relevant to you as long as there are only two outomes. For example:</p>
<ul>
<li>success = child – failure = adult</li>
<li>success = acceptable – failure = unacceptable</li>
<li>success = SVO – failure = SOV</li>
<li>…</li>
</ul>
<p>A good way of understanding the binomial distribution is to think of a coin-flip experiment. Imagine that you have a fair coin and you flip the coin 10 times. What is the probability that you will have 5 heads (i.e. successes)?</p>
<p><img src="main_files/figure-html/unnamed-chunk-279-1.png" width="672" /></p>
<p>To get the actual probability values in R, we can use the <code>dbinom()</code> function.</p>
<div class="sourceCode" id="cb580"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb580-1"><a href="logistic-regression.html#cb580-1" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">10</span> <span class="co">#number of trials</span></span>
<span id="cb580-2"><a href="logistic-regression.html#cb580-2" tabindex="-1"></a>p <span class="ot">=</span> <span class="fl">0.5</span> <span class="co">#probability of success (e.g. heads)</span></span>
<span id="cb580-3"><a href="logistic-regression.html#cb580-3" tabindex="-1"></a>s <span class="ot">=</span> <span class="dv">5</span> <span class="co">#number of successes in n trails (e.g. number of heads in 10 trials)</span></span>
<span id="cb580-4"><a href="logistic-regression.html#cb580-4" tabindex="-1"></a></span>
<span id="cb580-5"><a href="logistic-regression.html#cb580-5" tabindex="-1"></a><span class="fu">dbinom</span>(s,n,p)</span></code></pre></div>
<pre class="r-output"><code>## [1] 0.2460938</code></pre>
<p>Try it with different parameters to see how the probabilites change.</p>
<p>Notice that the binomial distribution is a discrete distribution (not continuous) but the plot looks very similar to a normal distribution especially when the number of trials is at or above 30.</p>
<p><img src="main_files/figure-html/unnamed-chunk-281-1.png" width="672" /></p>
<p><img src="main_files/figure-html/unnamed-chunk-282-1.png" width="672" /></p>
</div>
<div id="bernoulli-distribution" class="section level4 hasAnchor" number="12.2.1.2">
<h4><span class="header-section-number">12.2.1.2</span> Bernoulli distribution<a href="logistic-regression.html#bernoulli-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>A Bernoulli distribution is a special case of a binomial distribution with where the number of trials is 1. The only relevant parameter is the <span class="math inline">\(p\)</span>. Thus, Bernoulli distribution for a fair coin would look like the following.</p>
<p><img src="main_files/figure-html/unnamed-chunk-283-1.png" width="672" /></p>
<p>What if the coin were a bit unfair. Assume that you want to cheat but not too much to avoid getting caught.</p>
<p><img src="main_files/figure-html/unnamed-chunk-284-1.png" width="672" /></p>
<p>Finally, going back to our toy example from above about the length of utterances. Notice that this is also a Bernoulli distribution.</p>
<p><img src="main_files/figure-html/unnamed-chunk-285-1.png" width="672" /></p>
<p>Bernoulli distribution will vary based on a single parameter <span class="math inline">\(p\)</span>, which is the probability of success for a given condition.</p>
</div>
</div>
</div>
<div id="logistic-regression-1" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> Logistic Regression<a href="logistic-regression.html#logistic-regression-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Remember that in <strong>linear regression</strong>, the goal was to estimate the model parameters that can describe a line.</p>
<p><span class="math display">\[ \underbrace{Y}_{\text{dependent variable}} =
            \overbrace{\underbrace{a}_{\text{intercept}}}^{\text{additive term}} +
            \overbrace{\underbrace{b}_{\text{slope}} * \underbrace{X}_{\text{predictor}}}^{\text{additive term}} \]</span></p>
<p>In other words, our model took input some data, assumed that the variance in the data can be described by a line, then tried to estimate the parameters (i.e. intercept and slope). For example, we tried to estimate the taxi fare cost and our linear model could predict it as follows:</p>
<ul>
<li>cost = Intercept + Slope * Distance (in km)</li>
<li>cost = 20 + 14 * 5</li>
</ul>
<p>The values for the intercept and the slope were estimated by the model after analyzing the input data. The output of the model (i.e. the cost) is an <strong>arbitrary number</strong> (e.g. 90 TL).</p>
<p>In <strong>logistic regression</strong>, we don’t want an arbitrary number. Instead, we want a <strong>category</strong> (e.g. adult or child) along with a <strong>probability</strong>. In fact, what we need is a probability for success and the Bernoulli distribution will handle the rest.</p>
<ul>
<li><span class="math inline">\(y \sim Bernoulli(p)\)</span>
<ul>
<li>read as <em><span class="math inline">\(y\)</span> as a function of Bernoulli(p)</em></li>
<li><span class="math inline">\(y\)</span> is the predicted category</li>
</ul></li>
</ul>
<p>So, we need a way to convert <strong>arbitrary numbers</strong> (output of the linear equation) to <strong>probabilities</strong>. Remember that probabilities range between [0,1].</p>
<p>In mathematics, there is a really nice function that will squeeze arbitrary numbers between [0,1]. The name of this function is the <strong>logistic function</strong>.</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-286"></span>
<img src="img/logis.png" alt="Logistic Function"  />
<p class="caption">
Figure 12.1: Logistic Function
</p>
</div>
<p>In R, we can use the <code>plogis()</code> function to apply the logistic function to an arbitrary number. Try the following code with various values to see what you get.</p>
<div class="sourceCode" id="cb582"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb582-1"><a href="logistic-regression.html#cb582-1" tabindex="-1"></a><span class="fu">plogis</span>(<span class="dv">90</span>)</span></code></pre></div>
<pre class="r-output"><code>## [1] 1</code></pre>
<div class="sourceCode" id="cb584"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb584-1"><a href="logistic-regression.html#cb584-1" tabindex="-1"></a><span class="fu">plogis</span>(<span class="fl">2.1</span>)</span></code></pre></div>
<pre class="r-output"><code>## [1] 0.8909032</code></pre>
<div class="sourceCode" id="cb586"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb586-1"><a href="logistic-regression.html#cb586-1" tabindex="-1"></a><span class="fu">plogis</span>(<span class="dv">0</span>)</span></code></pre></div>
<pre class="r-output"><code>## [1] 0.5</code></pre>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb588-1"><a href="logistic-regression.html#cb588-1" tabindex="-1"></a><span class="fu">plogis</span>(<span class="sc">-</span><span class="dv">3</span>)</span></code></pre></div>
<pre class="r-output"><code>## [1] 0.04742587</code></pre>
<p>This is nice because we can use the logistic function to convert the output of our linear function to probabilities. Once we have the probabilities, we can get a Bernoulli distribution to predict the category we are interested in.</p>
<p>By now, it should be clear where the name <strong>logistic regression</strong> comes from.</p>
<div id="log-odds-logits" class="section level3 hasAnchor" number="12.3.1">
<h3><span class="header-section-number">12.3.1</span> Log Odds &amp; Logits<a href="logistic-regression.html#log-odds-logits" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In a nutshell, the logistic regression model works as follows:</p>
<ul>
<li><span class="math inline">\(p = logistic(output)\)</span></li>
<li><span class="math inline">\(y \sim Bernoulli(p)\)</span></li>
</ul>
<p>You calculate some output:</p>
<ul>
<li>(<span class="math inline">\(output = Intercept + Slope * input\)</span>)</li>
</ul>
<p>You convert it to a probability:</p>
<ul>
<li><span class="math inline">\(p = logistic(output)\)</span></li>
</ul>
<p>The rest is just a Bernoulli distribution with the parameter <span class="math inline">\(p\)</span>:</p>
<ul>
<li><span class="math inline">\(y \sim Bernoulli(p)\)</span></li>
</ul>
<p>There is an important difference though. In <strong>linear regression</strong> the output is just an arbitrary number :</p>
<ul>
<li>(<span class="math inline">\(output = Intercept + Slope * input\)</span>).</li>
</ul>
<p>In <strong>logistic regression</strong>, the model output is a <strong>logit</strong>. So, we calculate the probability of logits rather than arbitrary numbers.</p>
<ul>
<li><span class="math inline">\(logit(p)= intercept + slope * x\)</span></li>
</ul>
<div id="odds-log-odds-and-logits" class="section level4 hasAnchor" number="12.3.1.1">
<h4><span class="header-section-number">12.3.1.1</span> Odds, Log Odds, and Logits<a href="logistic-regression.html#odds-log-odds-and-logits" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Yon understand <strong>logits</strong>, we need to understand the concept of <strong>odds</strong>. You must have heard questions like:</p>
<ul>
<li>What are the <strong>odds</strong> that our team will win this week?</li>
<li>The <strong>odds</strong> are in my favor.</li>
<li>The <strong>odds</strong> are 1 to 1.</li>
</ul>
<p>The <strong>odds</strong> express the probability of an event occurring (p) over the probability of an event not occurring (1 − p).</p>
<ul>
<li><span class="math inline">\(odds(X=win) = \frac{P(X=win)}{1-P(X=win)}\)</span></li>
</ul>
<p><strong>Logits</strong> are log odds (<span class="math inline">\(log(odd)\)</span>). Converting the odds to log odds (i.e. logits) turns them into a <strong>continuous scale</strong> from negative infinity to positive infinity. Thus, it allows us to model <strong>categorical outcomes</strong> similar to <strong>continuous outcomes</strong>.</p>
<table>
<thead>
<tr class="header">
<th align="left"><strong>Probability</strong></th>
<th align="left"><strong>Odds</strong></th>
<th align="left"><strong>log odds (logits</strong>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0.1</td>
<td align="left">0.11 to 1</td>
<td align="left">–2.20</td>
</tr>
<tr class="even">
<td align="left">0.4</td>
<td align="left">0.67 to 1</td>
<td align="left">–0.41</td>
</tr>
<tr class="odd">
<td align="left">0.5</td>
<td align="left">1 to 1</td>
<td align="left">0.00</td>
</tr>
<tr class="even">
<td align="left">0.8</td>
<td align="left">4 to 1</td>
<td align="left">+1.39</td>
</tr>
<tr class="odd">
<td align="left">0.9</td>
<td align="left">9 to 1</td>
<td align="left">+2.20</td>
</tr>
</tbody>
</table>
<p><strong>Logistic Regression</strong> models estimate coefficients (intercept and slope) as <strong>logits</strong>. We can turn logits into probabilities, simply by feeding them into the <strong>logistic function</strong>.</p>
</div>
</div>
</div>
<div id="logistic-regression-in-r" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Logistic Regression in R<a href="logistic-regression.html#logistic-regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="data" class="section level3 hasAnchor" number="12.4.1">
<h3><span class="header-section-number">12.4.1</span> Data<a href="logistic-regression.html#data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let us see <strong>logistic regression</strong> in action by using it on a dataset from Bodo Winter’s book. For this task, we will use the <code>speech_errors</code> dataset.</p>
<div class="sourceCode" id="cb590"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb590-1"><a href="logistic-regression.html#cb590-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb590-2"><a href="logistic-regression.html#cb590-2" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;~/ling_411/data/speech_errors.csv&#39;</span>)</span></code></pre></div>
<pre><code>## Rows: 40 Columns: 2
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (2): BAC, speech_error
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb592-1"><a href="logistic-regression.html#cb592-1" tabindex="-1"></a>data</span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 40 × 2
##       BAC speech_error
##     &lt;dbl&gt;        &lt;dbl&gt;
##  1 0.0737            0
##  2 0.0973            0
##  3 0.234             0
##  4 0.138             1
##  5 0.0933            0
##  6 0.262             1
##  7 0.357             0
##  8 0.237             1
##  9 0.352             1
## 10 0.379             1
## # ℹ 30 more rows</code></pre>
<p>The data consists of two columns:</p>
<ul>
<li><code>BAC</code>: A continuous value representing the level of Blood Alcohol Concentration</li>
<li><code>speech_error</code>: A binary value representing the presence and absence of a speech error.
<ul>
<li>1 = speech error</li>
<li>0 = no speech error</li>
</ul></li>
</ul>
</div>
<div id="model" class="section level3 hasAnchor" number="12.4.2">
<h3><span class="header-section-number">12.4.2</span> Model<a href="logistic-regression.html#model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In R, we will use the <code>glm()</code> function, which stands for <strong>generalized linear model</strong>. <code>glm()</code> takes input</p>
<ul>
<li>an output variable,</li>
<li>predictors</li>
<li>a dataset</li>
<li>a <strong>family</strong> parameter, which will be <code>'binomial'</code> for our purposes</li>
</ul>
<div class="sourceCode" id="cb594"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb594-1"><a href="logistic-regression.html#cb594-1" tabindex="-1"></a>speech_error_model <span class="ot">&lt;-</span> <span class="fu">glm</span>(speech_error <span class="sc">~</span> BAC, <span class="at">data =</span> data,</span>
<span id="cb594-2"><a href="logistic-regression.html#cb594-2" tabindex="-1"></a>                          <span class="at">family =</span> <span class="st">&#39;binomial&#39;</span></span>
<span id="cb594-3"><a href="logistic-regression.html#cb594-3" tabindex="-1"></a>                          )</span></code></pre></div>
<p>Simple as that, we have modeled the presence and absence of speech errors as a function of blood alcohol concentration using <strong>logistic regression</strong>. Let us inspect the model coefficients to understand what our model learnt from the data.</p>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb595-1"><a href="logistic-regression.html#cb595-1" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb595-2"><a href="logistic-regression.html#cb595-2" tabindex="-1"></a><span class="fu">tidy</span>(speech_error_model)</span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)    -3.64      1.12     -3.24 0.00118 
## 2 BAC            16.1       4.86      3.32 0.000903</code></pre>
<p><strong>We learn a few things:</strong></p>
<ul>
<li>The slope of BAC is positive (16.1). This means that an increase in BAC will lead to an increase in speech errors.</li>
<li>We also see that the p &lt; 0.05. This indicates that our conclusion is statistically significant.</li>
<li>Remember that the output of logistic regression is a <strong>logit</strong>. Thus our coefficients (intercept and slope) are in logit units.</li>
</ul>
<p><strong>The results of the model can be reported as:</strong></p>
<ul>
<li>There was a reliable effect of BAC (logit coefficient: +16.11, SE = 4.86, z=3.3, p = 0.0009).</li>
</ul>
</div>
<div id="from-logits-to-probabilities" class="section level3 hasAnchor" number="12.4.3">
<h3><span class="header-section-number">12.4.3</span> From logits to probabilities<a href="logistic-regression.html#from-logits-to-probabilities" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Logits are a bit confusing. Let us turn our logits to probabilities to get a more intuitive understanding of the model results.</p>
<p>First, let us convert the intecept to a probability. Remember that the intercept is the logit for BAC = 0.</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb597-1"><a href="logistic-regression.html#cb597-1" tabindex="-1"></a>intercept <span class="ot">&lt;-</span> <span class="fu">tidy</span>(speech_error_model)<span class="sc">$</span>estimate[<span class="dv">1</span>]</span>
<span id="cb597-2"><a href="logistic-regression.html#cb597-2" tabindex="-1"></a>slope <span class="ot">&lt;-</span> <span class="fu">tidy</span>(speech_error_model)<span class="sc">$</span>estimate[<span class="dv">2</span>]</span>
<span id="cb597-3"><a href="logistic-regression.html#cb597-3" tabindex="-1"></a></span>
<span id="cb597-4"><a href="logistic-regression.html#cb597-4" tabindex="-1"></a><span class="fu">plogis</span>(intercept)</span></code></pre></div>
<pre class="r-output"><code>## [1] 0.02549508</code></pre>
<p>This shows that a sober person will make a speech error with the probability <span class="math inline">\(P=0.025\)</span>, quite a small probability.</p>
<p>Now let us check the probability of a person with a BAC of 0.4 making speech errors.</p>
<div class="sourceCode" id="cb599"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb599-1"><a href="logistic-regression.html#cb599-1" tabindex="-1"></a>logit <span class="ot">&lt;-</span> intercept <span class="sc">+</span> slope <span class="sc">*</span> <span class="fl">0.3</span></span>
<span id="cb599-2"><a href="logistic-regression.html#cb599-2" tabindex="-1"></a>probablity <span class="ot">&lt;-</span> <span class="fu">plogis</span>(logit)</span>
<span id="cb599-3"><a href="logistic-regression.html#cb599-3" tabindex="-1"></a>probablity</span></code></pre></div>
<pre class="r-output"><code>## [1] 0.7670986</code></pre>
<p>That is a huge jump. Our model predicts that someone with a <span class="math inline">\(BAC = 0.3\)</span> will make a speech error with a probability <span class="math inline">\(P = 0.76\)</span>, a lot more likely.</p>
<p>Let’s see what the data looks like.</p>
<div class="sourceCode" id="cb601"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb601-1"><a href="logistic-regression.html#cb601-1" tabindex="-1"></a>data_bac_0<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">filter</span>(data,BAC<span class="sc">&gt;=</span><span class="fl">0.3</span>)</span>
<span id="cb601-2"><a href="logistic-regression.html#cb601-2" tabindex="-1"></a>data_bac_0<span class="fl">.3</span></span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 9 × 2
##     BAC speech_error
##   &lt;dbl&gt;        &lt;dbl&gt;
## 1 0.357            0
## 2 0.352            1
## 3 0.379            1
## 4 0.306            0
## 5 0.382            1
## 6 0.308            1
## 7 0.394            1
## 8 0.332            1
## 9 0.395            1</code></pre>
<p>Not bad. Using <strong>logistic regression</strong> we can:</p>
<ul>
<li>understand the relationship between variables where the outcome is categorical (two categories)</li>
<li>make predictions</li>
</ul>
<p>Now that we have the model coefficients, we can predict some values and plot them.</p>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb603-1"><a href="logistic-regression.html#cb603-1" tabindex="-1"></a>BAC_vals <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.4</span>, <span class="fl">0.01</span>)</span>
<span id="cb603-2"><a href="logistic-regression.html#cb603-2" tabindex="-1"></a>y_preds <span class="ot">&lt;-</span> <span class="fu">plogis</span>(intercept <span class="sc">+</span> slope <span class="sc">*</span> BAC_vals)</span>
<span id="cb603-3"><a href="logistic-regression.html#cb603-3" tabindex="-1"></a></span>
<span id="cb603-4"><a href="logistic-regression.html#cb603-4" tabindex="-1"></a>mdl_preds <span class="ot">&lt;-</span> <span class="fu">tibble</span>(BAC_vals, y_preds)</span>
<span id="cb603-5"><a href="logistic-regression.html#cb603-5" tabindex="-1"></a>mdl_preds</span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 41 × 2
##    BAC_vals y_preds
##       &lt;dbl&gt;   &lt;dbl&gt;
##  1     0     0.0255
##  2     0.01  0.0298
##  3     0.02  0.0349
##  4     0.03  0.0407
##  5     0.04  0.0475
##  6     0.05  0.0553
##  7     0.06  0.0644
##  8     0.07  0.0748
##  9     0.08  0.0867
## 10     0.09  0.100 
## # ℹ 31 more rows</code></pre>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb605-1"><a href="logistic-regression.html#cb605-1" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">x =</span> BAC, <span class="at">y =</span> speech_error)) <span class="sc">+</span></span>
<span id="cb605-2"><a href="logistic-regression.html#cb605-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">4</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb605-3"><a href="logistic-regression.html#cb605-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> mdl_preds,</span>
<span id="cb605-4"><a href="logistic-regression.html#cb605-4" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">x =</span> BAC_vals, <span class="at">y =</span> y_preds)) <span class="sc">+</span></span>
<span id="cb605-5"><a href="logistic-regression.html#cb605-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="main_files/figure-html/unnamed-chunk-294-1.png" width="672" /></p>
</div>
<div id="dative-dataset" class="section level3 hasAnchor" number="12.4.4">
<h3><span class="header-section-number">12.4.4</span> Dative Dataset<a href="logistic-regression.html#dative-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let us now turn to another dataset we discussed earlier in the semester. This is the dative dataset by Bresnan et al. (2007). The main goal of the experiment was to identify the factors in determining the dative alternation in English:</p>
<ul>
<li>Alex gave Sam a book. (NP NP)</li>
<li>Alex gave a book to Sam. (NP PP)</li>
</ul>
<p>The dative data set can be found directly using the <code>languageR</code> library. Let us take a look at the columns in the dataset and also some values to get a sense of what it looks like.</p>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb606-1"><a href="logistic-regression.html#cb606-1" tabindex="-1"></a><span class="fu">library</span>(languageR)</span>
<span id="cb606-2"><a href="logistic-regression.html#cb606-2" tabindex="-1"></a></span>
<span id="cb606-3"><a href="logistic-regression.html#cb606-3" tabindex="-1"></a><span class="fu">colnames</span>(dative)</span></code></pre></div>
<pre class="r-output"><code>##  [1] &quot;Speaker&quot;                &quot;Modality&quot;               &quot;Verb&quot;                  
##  [4] &quot;SemanticClass&quot;          &quot;LengthOfRecipient&quot;      &quot;AnimacyOfRec&quot;          
##  [7] &quot;DefinOfRec&quot;             &quot;PronomOfRec&quot;            &quot;LengthOfTheme&quot;         
## [10] &quot;AnimacyOfTheme&quot;         &quot;DefinOfTheme&quot;           &quot;PronomOfTheme&quot;         
## [13] &quot;RealizationOfRecipient&quot; &quot;AccessOfRec&quot;            &quot;AccessOfTheme&quot;</code></pre>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="logistic-regression.html#cb608-1" tabindex="-1"></a><span class="fu">head</span>(dative,<span class="dv">3</span>)</span></code></pre></div>
<pre class="r-output"><code>##   Speaker Modality Verb SemanticClass LengthOfRecipient AnimacyOfRec DefinOfRec
## 1    &lt;NA&gt;  written feed             t                 1      animate   definite
## 2    &lt;NA&gt;  written give             a                 2      animate   definite
## 3    &lt;NA&gt;  written give             a                 1      animate   definite
##     PronomOfRec LengthOfTheme AnimacyOfTheme DefinOfTheme PronomOfTheme
## 1    pronominal            14      inanimate   indefinite nonpronominal
## 2 nonpronominal             3      inanimate   indefinite nonpronominal
## 3 nonpronominal            13      inanimate     definite nonpronominal
##   RealizationOfRecipient AccessOfRec AccessOfTheme
## 1                     NP       given           new
## 2                     NP       given           new
## 3                     NP       given           new</code></pre>
<p>Next, let us take a look at the possible values for the RealizationOfRecipient column to see what they look like.</p>
<div class="sourceCode" id="cb610"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb610-1"><a href="logistic-regression.html#cb610-1" tabindex="-1"></a><span class="fu">levels</span>(dative<span class="sc">$</span>RealizationOfRecipient)</span></code></pre></div>
<pre class="r-output"><code>## [1] &quot;NP&quot; &quot;PP&quot;</code></pre>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="logistic-regression.html#cb612-1" tabindex="-1"></a><span class="fu">levels</span>(dative<span class="sc">$</span>AnimacyOfRec)</span></code></pre></div>
<pre class="r-output"><code>## [1] &quot;animate&quot;   &quot;inanimate&quot;</code></pre>
<p>OK so, we have only two values. This is a good task for logistic regression. Let us for now model the RealizationOfRecipient as a function of the AnimacyOfRec.</p>
<div class="sourceCode" id="cb614"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb614-1"><a href="logistic-regression.html#cb614-1" tabindex="-1"></a>model_1 <span class="ot">&lt;-</span> model <span class="ot">&lt;-</span> <span class="fu">glm</span>(RealizationOfRecipient <span class="sc">~</span> AnimacyOfRec, dative, <span class="at">family=</span><span class="st">&#39;binomial&#39;</span>)</span>
<span id="cb614-2"><a href="logistic-regression.html#cb614-2" tabindex="-1"></a></span>
<span id="cb614-3"><a href="logistic-regression.html#cb614-3" tabindex="-1"></a><span class="fu">tidy</span>(model)</span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 2 × 5
##   term                  estimate std.error statistic   p.value
##   &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)              -1.15    0.0426    -27.1  1.15e-161
## 2 AnimacyOfRecinanimate     1.23    0.136       9.02 1.87e- 19</code></pre>
<div class="sourceCode" id="cb616"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb616-1"><a href="logistic-regression.html#cb616-1" tabindex="-1"></a>model_2 <span class="ot">&lt;-</span><span class="fu">glm</span>(RealizationOfRecipient <span class="sc">~</span> AnimacyOfRec<span class="sc">+</span>LengthOfTheme<span class="sc">+</span>LengthOfRecipient<span class="sc">+</span>AnimacyOfTheme, dative, <span class="at">family=</span><span class="st">&#39;binomial&#39;</span>)</span>
<span id="cb616-2"><a href="logistic-regression.html#cb616-2" tabindex="-1"></a></span>
<span id="cb616-3"><a href="logistic-regression.html#cb616-3" tabindex="-1"></a><span class="fu">tidy</span>(model)</span></code></pre></div>
<pre class="r-output"><code>## # A tibble: 2 × 5
##   term                  estimate std.error statistic   p.value
##   &lt;chr&gt;                    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1 (Intercept)              -1.15    0.0426    -27.1  1.15e-161
## 2 AnimacyOfRecinanimate     1.23    0.136       9.02 1.87e- 19</code></pre>
<p>Now let us compare the two models.</p>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="logistic-regression.html#cb618-1" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span></code></pre></div>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="logistic-regression.html#cb622-1" tabindex="-1"></a>lr_test <span class="ot">&lt;-</span> <span class="fu">lrtest</span>(model_1, model_2)</span>
<span id="cb622-2"><a href="logistic-regression.html#cb622-2" tabindex="-1"></a><span class="fu">print</span>(lr_test)</span></code></pre></div>
<pre class="r-output"><code>## Likelihood ratio test
## 
## Model 1: RealizationOfRecipient ~ AnimacyOfRec
## Model 2: RealizationOfRecipient ~ AnimacyOfRec + LengthOfTheme + LengthOfRecipient + 
##     AnimacyOfTheme
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)    
## 1   2 -1831.1                         
## 2   5 -1379.5  3 903.19  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="testing-the-model" class="section level2 hasAnchor" number="12.5">
<h2><span class="header-section-number">12.5</span> Testing the model<a href="logistic-regression.html#testing-the-model" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="logistic-regression.html#cb624-1" tabindex="-1"></a>test_data <span class="ot">&lt;-</span> <span class="fu">select</span>(dative, AnimacyOfRec,LengthOfTheme,LengthOfRecipient,AnimacyOfTheme,RealizationOfRecipient)</span>
<span id="cb624-2"><a href="logistic-regression.html#cb624-2" tabindex="-1"></a><span class="fu">head</span>(test_data)</span></code></pre></div>
<pre class="r-output"><code>##   AnimacyOfRec LengthOfTheme LengthOfRecipient AnimacyOfTheme
## 1      animate            14                 1      inanimate
## 2      animate             3                 2      inanimate
## 3      animate            13                 1      inanimate
## 4      animate             5                 1      inanimate
## 5      animate             3                 2      inanimate
## 6      animate             4                 2      inanimate
##   RealizationOfRecipient
## 1                     NP
## 2                     NP
## 3                     NP
## 4                     NP
## 5                     NP
## 6                     NP</code></pre>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="logistic-regression.html#cb626-1" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb626-2"><a href="logistic-regression.html#cb626-2" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, <span class="at">newdata =</span> test_data, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb626-3"><a href="logistic-regression.html#cb626-3" tabindex="-1"></a></span>
<span id="cb626-4"><a href="logistic-regression.html#cb626-4" tabindex="-1"></a></span>
<span id="cb626-5"><a href="logistic-regression.html#cb626-5" tabindex="-1"></a><span class="co"># For binary classification, calculate accuracy</span></span>
<span id="cb626-6"><a href="logistic-regression.html#cb626-6" tabindex="-1"></a>predicted_classes <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predictions <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="st">&#39;PP&#39;</span>, <span class="st">&#39;NP&#39;</span>)</span>
<span id="cb626-7"><a href="logistic-regression.html#cb626-7" tabindex="-1"></a></span>
<span id="cb626-8"><a href="logistic-regression.html#cb626-8" tabindex="-1"></a></span>
<span id="cb626-9"><a href="logistic-regression.html#cb626-9" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">mean</span>(predicted_classes <span class="sc">==</span> test_data<span class="sc">$</span>RealizationOfRecipient)</span>
<span id="cb626-10"><a href="logistic-regression.html#cb626-10" tabindex="-1"></a></span>
<span id="cb626-11"><a href="logistic-regression.html#cb626-11" tabindex="-1"></a>accuracy</span></code></pre></div>
<pre class="r-output"><code>## [1] 0.7425682</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="effect-size-significance.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="modeling-poisson-distribution.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/11-logistic_regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["main.pdf", "main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
